### ISSUE TITLE
Mac下面录浏览器很糊涂，清晰度很低，不知道怎么解决？

### ISSUE THREAD

**Issue by Xucheng80** [lihaoyun6/QuickRecorder#10]
Mac下面录浏览器很糊涂，清晰度很低，不知道怎么解决？

**Comment by lihaoyun6** [comment]
您好，有具体的录屏样片可以发来我看一下吗

**Comment by qq3450095290** [comment]
> 您好，有具体的录屏样片可以发来我看一下吗

我也是，刚刚下载安装试用了一下，参数都是设置默认的，录制好的视频打开，确实画质有点差。我的电脑是 M1 Pro 的，macOS 是 14.4.1，录制视频时找不到如何打开演讲者画面，虽然设置里是打开了的

**Comment by lihaoyun6** [comment]
> > 您好，有具体的录屏样片可以发来我看一下吗
> 
> 我也是，刚刚下载安装试用了一下，参数都是设置默认的，录制好的视频打开，确实画质有点差。我的电脑是 M1 Pro 的，macOS 是 14.4.1，录制视频时找不到如何打开演讲者画面，虽然设置里是打开了的

可不可以随便录制一段什么内容发过来看看

**Comment by Xucheng80** [comment]
https://github.com/lihaoyun6/QuickRecorder/assets/168386415/a4df2dc5-2e29-40c3-85ad-877083297f95



> 您好，有具体的录屏样片可以发来我看一下吗


https://github.com/lihaoyun6/QuickRecorder/assets/168386415/1fc084c3-501e-45ee-b50b-b624f7da6d17

**Comment by lihaoyun6** [comment]
<img width="1424" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/a8fab974-396e-4c71-8b17-fe5f0e27c12d">
因为您选择的不是chrome窗口的本体, 而是这个弹出来的"翻译此页"对话框...这个对话框真的很烦人, 他会干扰视线

**Comment by Xucheng80** [comment]
有办法可以解决吗？或者能否把 chrome 全屏后录？如果 chrome 全屏后，在主屏打开 QuickRecorder 就找不到 chrome

**Comment by Xucheng80** [comment]
再试了一下，如果用录制窗口内容，只能识别一个 chrome 窗口（但 chrome 里面有 10 多个页面），如果录那个窗口就是低分辨率。
<img width="1440" alt="截屏2024-05-01 16 35 41" src="https://github.com/lihaoyun6/QuickRecorder/assets/168386415/1058223d-93e0-4d6b-b4c9-d8d2106c2f7c">

**Comment by lihaoyun6** [comment]
> 再试了一下，如果用录制窗口内容，只能识别一个 chrome 窗口（但 chrome 里面有 10 多个页面），如果录那个窗口就是低分辨率。 

你这样截图我就知道是什么情况了. 因为QuickRecorder会在开始录制之前获取窗口信息以确定输出视频的尺寸.
但是你现在这样把Chrome放在"台前调度"视图里, QuickRecorder获取到的窗口尺寸就不是实际的尺寸, 而是这个侧边栏缩略图的尺寸
所以你需要先把窗口从台前调度侧边栏拉出来, 让他正常显示在桌面上, 然后再开始录屏就好了
