### ISSUE TITLE
Microphone recording may be interrupted and become incorrect, if another app uses the microphone, while recording the microphone. 录制麦克风时，若有其他程序使用麦克风，则麦克风录制或将出错。

### ISSUE THREAD

**Issue by shaojiaxu** [lihaoyun6/QuickRecorder#100]
以下为2个实例。

### 1
使用QQ的屏幕共享和语音通话，在启用QQ的麦克风后，开始使用QR录制。
<img width="892" alt="截圖 2024-07-10 18 22 37" src="https://github.com/lihaoyun6/QuickRecorder/assets/47326084/a571131a-6d08-48cf-bb1b-68450d03fea9">
<img width="703" alt="截圖 2024-07-10 18 44 13" src="https://github.com/lihaoyun6/QuickRecorder/assets/47326084/be53dd90-593c-46f2-9b90-a8722126f4c9">

￼

录制一开始是正常运行的，中间突然出错，截取了开始出问题的那一段。

<img width="1440" alt="截圖 2024-07-10 19 22 42" src="https://github.com/lihaoyun6/QuickRecorder/assets/47326084/04da13ec-1545-4367-9707-d6a5e81ade74">

全程没有重启过QR。

我挂断了QQ，并重启QQ的屏幕共享和语音通话后，QQ语音正常，QR录制App声音正常，QR录制的麦克风为严重杂音，不能分辨人声。

视频文件比较大，如果作者您需要，请不要客气，联系我。

### 2
QR设置同上。

参加在线会议，在网页上启用麦克风后，QR完全中断麦克风录制（第二条音轨）。

<img width="1440" alt="截圖 2024-07-10 19 26 46" src="https://github.com/lihaoyun6/QuickRecorder/assets/47326084/99c39e6a-50fa-4e91-9233-deed47ffab01">

同样，您若需要原文件，请联系我。

**Comment by shaojiaxu** [comment]
对不起，不小心发布了，还没写完，我尽快。

**Comment by shaojiaxu** [comment]
> 对不起，不小心发布了，还没写完，我尽快。

写完了，本来想把视频发上来，不会操作，试着导出双音轨的视频，没找到设置码率的入口，直接导出 H.264，6分钟达2GB，夸张。

**Comment by lihaoyun6** [comment]
<img width="478" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/0de5d7b5-0911-4a9f-907f-0e35b5dca8aa">

虽然新版QuickRecorder支持选择特定麦克风, 但很难保证兼容性. 我个人还是建议使用"系统默认"选项(此选项将使用"系统偏好设置"中选择的默认麦克风. 请勿在录制过程中切换默认麦克风). 这个选项的兼容性会好很多. 你可以试试看

**Comment by shaojiaxu** [comment]
> <img alt="image" width="478" src="https://private-user-images.githubusercontent.com/16348097/347645715-0de5d7b5-0911-4a9f-907f-0e35b5dca8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTk3NTMsIm5iZiI6MTcyMDc1OTQ1MywicGF0aCI6Ii8xNjM0ODA5Ny8zNDc2NDU3MTUtMGRlNWQ3YjUtMDkxMS00YTlmLTkwN2YtMGUzNWI1ZGNhOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA0NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhN2ZmMDNjMGY3YTA2NWIzNzk5ZmUwMmVkMzY4YzA2MzE5MTliMDc3ODU1ZDJjOTcyZDVmNDk0MDg2YzNmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IEJwjtdJDDKVzDEdrNEQRl76wYtZoEnJI9vJRilvMqY"> <img alt="image" width="472" src="https://private-user-images.githubusercontent.com/16348097/347646085-5534357b-6cf7-4d72-b352-e00e123812c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTk3NTMsIm5iZiI6MTcyMDc1OTQ1MywicGF0aCI6Ii8xNjM0ODA5Ny8zNDc2NDYwODUtNTUzNDM1N2ItNmNmNy00ZDcyLWIzNTItZTAwZTEyMzgxMmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA0NDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1N2I1YTA4MWExOGNmZWNmZGMxYmU1YzcxM2U5NTJjYjU3NDI5NzM1YTU4OGY3YTM4M2E5MWUwOTExODYyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.75Zd6Pmr9BihRdJCfuNXFZg8fc3bdQdlwRFY7GBjoX8">
> 虽然新版QuickRecorder支持选择特定麦克风, 但很难保证兼容性. 我个人还是建议使用"系统默认"选项(此选项将使用"系统偏好设置"中选择的默认麦克风. 请勿在录制过程中切换默认麦克风). 这个选项的兼容性会好很多. 你可以试试看

谢谢！最近比较忙，我有时间会试试。
