### ISSUE TITLE
多窗口同时录制

### ISSUE THREAD

**Issue by RenjieTao** [lihaoyun6/QuickRecorder#106]
能不能支持多个屏幕（窗口）同时录制哈？

**Comment by lihaoyun6** [comment]
可以支持多个窗口同时录制, 但不只是多个屏幕同时录制

**Comment by lihaoyun6** [comment]
<img width="390" alt="image" src="https://github.com/user-attachments/assets/d05310ca-7723-42cc-b140-182d394d5da4">

多窗口录制只需要像这样在窗口选择器中将你需要录制的窗口都勾选上, 再开始录制就可以了
