### ISSUE TITLE
画面背景是黑色，在没有设置使用用户定义的背景情况下

### ISSUE THREAD

**Issue by wflixu** [lihaoyun6/QuickRecorder#11]
在录制 全屏画面是时，背景选择的是桌面背景，但是录出来的是视频是黑色背景

![image](https://github.com/lihaoyun6/QuickRecorder/assets/37231473/728ff1ae-7318-4441-9c07-ce7c60a82299)

**Comment by lihaoyun6** [comment]
问题已找到, 是参数值初始化方面出了问题, 将在下个版本中修复. 感谢支持

**Comment by lihaoyun6** [comment]
> QuickRecorder v1.1.1 更新日志:
    - 添加了 "演讲者前置延迟" 设置项, 如果启用 "大型" 视图导致录像损坏, 可尝试增大此值
    - 添加了通用摄像头叠加功能, 可在不支持 "演讲者前置" 的系统上使用
    - 添加了视频修剪器, 可以在结束录制后对录屏文件进行时间修剪
    - **修复了首次启动且使用录制全屏画面功能时壁纸变黑的问题**

这个问题应该已经在新版本中修复了. 但是不太好测试, 因为好像只有第一次启动的时候会遇到全屏壁纸黑屏的问题哈哈哈哈

**Comment by wflixu** [comment]
新版本已经解决了 👍
