### ISSUE TITLE
全屏化的窗口不能选择某个区域录制

### ISSUE THREAD

**Issue by y122972** [lihaoyun6/QuickRecorder#123]
这是个bug还是不能实现? 试了别的录屏也不能在全屏化的窗口圈一个区域录制

**Comment by lihaoyun6** [comment]
在最新的v1.4.7版本中, 我为QuickRecorder添加了"在全屏App空间中选择录制区域"的能力, 你可以更新试试

**Comment by lihaoyun6** [comment]
<img width="1366" alt="be3b05e09f7cc3da2a640a5faf3288af" src="https://github.com/user-attachments/assets/58821c69-743e-4357-873c-f7ecaa465819">

**Comment by y122972** [comment]
好的感谢!已赞助
