### ISSUE TITLE
可以把这一排操作按钮放到菜单栏么，或者是否可以加一个隐藏这排按钮的开关

### ISSUE THREAD

**Issue by xiaoliang-liu** [lihaoyun6/QuickRecorder#126]
<img width="212" alt="image" src="https://github.com/user-attachments/assets/605c1427-7b2a-4a6d-9c90-fd01502c7bd7">
因为有时在给客户进行腾讯会议展示我的屏幕时，显示我正在录屏，挺尴尬的

**Comment by lihaoyun6** [comment]
这一排按钮默认其实就是显示在菜单栏上的, 只有当你的菜单栏空间不够显示它们的时候, 它们才会变成独立的悬浮窗形式显示

**Comment by xiaoliang-liu** [comment]
> 这一排按钮默认其实就是显示在菜单栏上的, 只有当你的菜单栏空间不够显示它们的时候, 它们才会变成独立的悬浮窗形式显示

哦哦好的， 感谢

**Comment by lihaoyun6** [comment]
我在最新的v1.4.7版本中添加了一个新的选项"使用迷你控制器", 启用后, 控制按钮会更紧凑, 占用更少的菜单栏空间, 你可以更新一下试试

**Comment by lihaoyun6** [comment]
<img width="244" alt="image" src="https://github.com/user-attachments/assets/7651ef33-7d0b-4961-9cc4-e195218f2a3b">

<img width="124" alt="image" src="https://github.com/user-attachments/assets/8301bd24-2d2a-4ac7-bf60-c4808409026f">

**Comment by xiaoliang-liu** [comment]
> 我在最新的v1.4.7版本中添加了一个新的选项"使用迷你控制器", 启用后, 控制按钮会更紧凑, 占用更少的菜单栏空间, 你可以更新一下试试

好的，我试试，给你点赞👍👍👍
