### ISSUE TITLE
Support for cli based automation!

### ISSUE THREAD

**Issue by idvorkin** [lihaoyun6/QuickRecorder#128]
This tool is fantastic! Works perfectly out of the box.  Would be great if we could automate this via the command line, then we can control via any tool we'd like (for me alfred)! Happy to share automations out with folks!

I don't know how other tools do the bridge from cli to service, but if someone setup the server, I could probably put a client together.

**Comment by idvorkin** [comment]
Hymn, looks like sockets ... 

https://github.com/koekeishiya/yabai/blob/61bbb9b906a6c24d04292ec3c1f88f9c057d9e6c/src/yabai.c#L86

**Comment by lihaoyun6** [comment]
I added AppleScript support to QuickRecorder v1.4.8. You can use the built-in "Script Editor" app of macOS to view the syntax dictionary of QuickRecorder to learn how to use it.

**Please note: If you call QuickRecorder when it is not running, please use the `activate` keyword to activate it first, otherwise it will not work properly.**

*Example:*
```AppleScript
tell application "QuickRecorder"
	activate
	record window titled "Google" in application "Safari"
end tell
```

**Comment by idvorkin** [comment]
Wow, that was super fast. I'll give it a try thank you.

**Comment by idvorkin** [comment]
Hymn, when I try to open the app on a new computer, now it's saying it's not signed, does something need to be signed again?

**Comment by leoleoasd** [comment]
@lihaoyun6 Thanks, it worked!

BTW, Is there anyway to specify the output file name/path of the recording?

**Comment by leoleoasd** [comment]
FYI, you can run this
```
tell application "System Events" to get name of window of (processes whose name is "Google Chrome")
```
to get the title of a specific application.
