### ISSUE TITLE
Auto-Export qma Recording to mp3 on complete

### ISSUE THREAD

**Issue by akash-joshi** [lihaoyun6/QuickRecorder#138]
Hey @lihaoyun6 , I've been using quickrecorder extensively over the past few months for recording and transcribing all my meetings. Would it be possible to have an auto-export feature to mp3 on completion - so I can automate away the transcription step as well?

Thanks and lmk if you need help or have any Qs.

**Comment by lihaoyun6** [comment]
If the "Automatically export single-track audio" switch is turned on, will both .qma and .mp3 be created after recording, or will only .mp3 be left? Which do you think is better?

**Comment by lihaoyun6** [comment]
In v1.5.2, when you enable "Record Microphone to Main Track" QuickRecorder will generate both .qma and single track file (e.g. .mp3) after recording is complete.
