### ISSUE TITLE
录制后未生成视频文件

### ISSUE THREAD

**Issue by ice-wu5** [lihaoyun6/QuickRecorder#14]
1.录制完成后，在文件夹内没有找到新录制的文件。

2.录制完成后，裁剪器的视频，点击无法播放。截图如下：

<img width="943" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/58652693/9b93fa9b-dba2-4554-b8c8-a3b47878bc15">

**Comment by lihaoyun6** [comment]
请问使用的软件版本和macOS版本分别是多少?
出现问题时使用的是什么录制模式?(比如全屏/区域/应用/窗口)
录制时是否启用了其他高级功能?(比如演讲者前置/录制麦克风等)

**Comment by ice-wu5** [comment]
1.软件版本截图：
<img width="318" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/58652693/c5646f1f-6ede-4ed5-b39e-120bc7a93505">

2.macOS版本截图：
<img width="474" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/58652693/921b15ec-079f-4677-8400-c2e021aa4554">

3.录制模式：全屏

4.高级功能：录制麦克风
<img width="518" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/58652693/4c6f25a9-404c-4447-a6a0-ca61610bfb6a">

**Comment by lihaoyun6** [comment]
有没有尝试过换一个保存位置
