### ISSUE TITLE
录制结果饱和度低 Recording with low color saturation

### ISSUE THREAD

**Issue by Mobiusium** [lihaoyun6/QuickRecorder#15]
QuickRecorder 1.1.3(113)
MP4 H.264
录制饱和度低，颜色发灰。

<img width="1408" alt="截屏2024-05-01 14 28 23" src="https://github.com/lihaoyun6/QuickRecorder/assets/36825968/95427519-dcb0-453b-b928-5c88efa85161">
左为录制结果，右为截图。

**Comment by lihaoyun6** [comment]
已经找到问题所在了, ScreenCapture Kit默认输出P3色域, 当来源流和目标文件色彩空间不匹配的时候就会出现限缩异常.
下个版本中会在视频设置里加入允许用户自定义像素格式和色彩空间的选项, 可以解决这个问题

**Comment by lihaoyun6** [comment]
<img width="1444" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/42a3f4bf-42a9-4964-9842-c9f7045318af">
右下角的是没修改前的默认输出样片, 左下角的是强制sRGB输出的样片. 可以看到左下角的色彩于原视频的差别更小

**Comment by lihaoyun6** [comment]
v1.1.4版本已发布, 默认将色彩空间设置为sRGB以解决大多数情况下的录像褪色问题. 也允许用户自由切换不同的色彩空间.
