### ISSUE TITLE
MacOS 下 1.5.9 版本录制失败 - 0kb

### ISSUE THREAD

**Issue by jaywhj** [lihaoyun6/QuickRecorder#152]
刚下载的 最新版 1.5.9，试用了一下：

1. `录制全屏` 和 `录制区域`，开始录制后，菜单栏时间不走，录出来是0kb，设置项没动，默认设置；
2. `录制窗口` 和 `录制应用程序`，则没有问题，可以正常录制；

录制参数如下：

![iShot_2024-12-17_23 00 05](https://github.com/user-attachments/assets/12bfa642-0653-4d90-8271-5e4cb7301b37)

<img width="163" alt="iShot_2024-12-17_22 51 51" src="https://github.com/user-attachments/assets/ea5224bb-22bd-4708-8844-4e4d7dbdc0ab" />

<br />系统版本：MacOS 12.7.6 , Apple M1.
QuickRecorder：1.5.9

**Comment by lihaoyun6** [comment]
macOS 12的适配我已经做烦了做吐了, 为什么你们不升级系统呢

**Comment by lihaoyun6** [comment]
哪怕升级到macOS13也能享受到很多"现代macOS"特性, 为什么要死守macOS12?

**Comment by lihaoyun6** [comment]
别跟我说"卡", 我试过丐版M1 MBA升级13甚至14系统, 一点都不会卡

**Comment by jaywhj** [comment]
> 哪怕升级到macOS13也能享受到很多"现代macOS"特性, 为什么要死守macOS12?

@lihaoyun6 
没有死守哈，我才刚接触到 QuickRecorder 不到1天，试用了一下发现了问题，给你们反馈一下而已，感觉你有点烦躁啊，跟你**讲讲**正常的用户心里是怎么想的：

1. 没有谁天天盯着个电脑系统，看看要不要升级，除非是遇到了问题，才会考虑，正常都是这样的；
2. 我电脑是20年的M1，不存在升级卡顿的问题，我也没担心过升级会卡，不可能，所以你想多了；
3. 我没遇到 QuickRecorder 之前，也不知道 12.x 使用这个app会有问题，你告知了后，我会考虑升级系统，不是什么问题；
4. 如果你烦了，也不想在 12.x 系列改来改去，你完全可以设置最低运行版本为 13，这样用户下载了没法运行，就知道要升级系统了，也不会给你添堵报bug；

**Comment by lihaoyun6** [comment]
没事, 因为被macOS跨版本那糟糕的ABI兼容性搞心态太久了. 有点崩溃
你遇到的问题我已经在v1.6.0版本中进行修复了, 亲测可以在macOS 12系统中正常录制全屏以及屏幕区域. 更新即可

**Comment by jaywhj** [comment]
测试过了，可用，👍
