### ISSUE TITLE
Incorrect extension is being generated

### ISSUE THREAD

**Issue by ravshansbox** [lihaoyun6/QuickRecorder#155]
Files are being saved as ".mp4.mp4.mp4" rather than ".mp4"

**Comment by lihaoyun6** [comment]
1. macOS version?
2. QuickRecorder version?
3. What screen content did you record?
4. Are you recording both the system sound and the microphone?

**Comment by ravshansbox** [comment]
1. MacOS 15.2
2. QuickRecorder 1.6.0
3. Full screen
4. Yes, recording both system and microphone

**Comment by lihaoyun6** [comment]
Can you show me your "Preferences" > "Output" page?

**Comment by ravshansbox** [comment]
Yeap

<img width="461" alt="image" src="https://github.com/user-attachments/assets/9a7a0014-a728-4554-a558-f39b009ef3be" />

**Comment by lihaoyun6** [comment]
This bug has been fixed in version 1.6.1

**Comment by ravshansbox** [comment]
Confirmed, thanks
