### ISSUE TITLE
如何发现移动设备

### ISSUE THREAD

**Issue by uliyanjun** [lihaoyun6/QuickRecorder#16]
打开软件，在移动设备下没发现 iPhone，请问我需要做什么设置吗
macOS: 13.6.6
iphone: 12 pro max(17.4.1)

**Comment by lihaoyun6** [comment]
目前仅支持有线连接，请使用数据线将iPhone或iPad连接到mac，并选择信任此mac，稍等1~3分钟左右就可以在quickrecorder中发现移动设备了

**Comment by uliyanjun** [comment]
> 目前仅支持有线连接，请使用数据线将iPhone或iPad连接到mac，并选择信任此mac，稍等1~3分钟左右就可以在quickrecorder中发现移动设备了

感谢🙏
