### ISSUE TITLE
录制完毕后没有产生视频文件，且需要手动开始录制

### ISSUE THREAD

**Issue by asakimio** [lihaoyun6/QuickRecorder#17]
使用的是最新版该软件和最新版macOS。具体问题如下：
1:开始录制后，状态栏的显示的录制时间不会走动，需要暂停再开始才能开始。
2:录制结束后，在默认选定的文件夹下找不到录屏文件。
这个软件默认情况下，选定的保存目录似乎是和系统截图选定的自定义目录相同的目录（我选定的系统截图保存的目录，是在iCloud的一个目录内）。当我在这个软件中把保存目录改为其他目录（~/Movies）后，以上两个问题就不再发生。
最初测试丢失的录屏文件，使用访达全盘搜索后也无法找到，推测并不是保存到了其他所不知道的目录，而是被丢弃了
希望能修复问题🙏

**Comment by lihaoyun6** [comment]
好的，问题已收到，我会进行检查。如您有任何其他发现，可随再来补充

**Comment by lihaoyun6** [comment]
排查了一下, 应该是默认读取到系统存储的截图路径并解析成路径url的时候, 对于iCloud路径的解析出了问题. 导致路径解析失败. 文件不是写到了错误的地方, 而是根本没有创建成功.
而只要是用户手动选的路径都可以正常解析, 哪怕是iCloud路径也可以. 所以会在新版本中修改默认设置, 不再自动检测遵循系统截图保存路径设置了.
