### ISSUE TITLE
录制出来的视频，帧数只有 40 多

### ISSUE THREAD

**Issue by powersee** [lihaoyun6/QuickRecorder#19]
感谢作者大佬开发了这款软件，录制时资源占用很低。

我使用的是 Mac mini M2 16GB 版，显示器是 4k60。

录制全屏画面时，CPU 和 GPU 占用都很低 30% 以下。

不过录制完的视频，使用 mediainfo 查看，帧数只有 40 多。

不知是否用的是可变帧率的问题？如果是的话，希望之后可以添加固定帧率的选项，感谢。

<img width="561" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/38074760/5f96366c-499d-4970-bbf3-794155209e31">

**Comment by lihaoyun6** [comment]
因为这里显示的其实是"平均帧率", 而QuickRecorder在写入文件的过程中是不会对长时间的静态画面重复写入相同帧的.
如果遇到画面保持静止不动的情况, QuickRecorder会停止实际的帧写入, 而是靠修改PTS时间码来保证视频同步的.
你可以试一下: 录制一段静止画面, 和录制一段动态画面(比如网页视频). 最终录制出来的文件显示的平均帧率是不同的
这样可以更大限度的压缩文件体积, 并且不会影响视频播放. 在画面发生变化的时候, 确实是按照你设定的60fps进行录制的.

**Comment by lihaoyun6** [comment]
并不是说整个视频都是40fps, 而是有的地方60, 有的地方10, 有的地方可能是1. mediainfo经过平均计算之后得出整段录屏的平均帧率是40多fps.
动态帧率和强行全程60fps的播放效果是一样的, 但是体积会小很多. 没有必要全程强制固定帧率

**Comment by powersee** [comment]
感谢大佬的回复。我明白您的意思。我也有试过，确实画面变化不多的情况下，录制出来的视频帧率，还会更低，甚至只有 10 多帧。这个应该和 OBS 里面的 VBR 是一样的吧。不知道大佬有没有考虑之后加入「固定帧率」CBR 的选项？

因为这个录制出来的视频，如果只是自己看，那其实无所谓，不过如果还要剪辑的话，可能还是全程都是 60 帧的会比较好。总之还是感谢大佬的辛苦付出，希望这款 APP 能让更多人知道。

**Comment by lihaoyun6** [comment]
嗯, 确实是会有这种需求, 那我考虑一下加入这个选项吧, 下个版本见

**Comment by lihaoyun6** [comment]
嘶. 不是个简单的问题. 研究了一下, 发现ScreenCapture给出的源视频流就是可变帧率的, 并且没有直接可以配置为固定帧率的选项. 
如果来源流就是这个样子的话, 那无论如何都需要进行重采样才能将其转换为固定帧率视频. 既然涉及到重采样了, 我感觉QuickRecorder就不要越俎代庖, 直接交给视频编辑软件来做就好了😂

**Comment by powersee** [comment]
😂 这样呀，那看来要录制固定帧率还是得使用 OBS 了，哈哈，再次多谢大佬的解答。👍🏻

**Comment by lihaoyun6** [comment]
> 😂 这样呀，那看来要录制固定帧率还是得使用 OBS 了，哈哈，再次多谢大佬的解答。👍🏻

其实不用的, QuickRecorder录制好的文件用ffmpeg之类的视频编码软件重新编码一下就可以变成固定帧率视频了.   
比如使用ffmpeg可以用这个命令就可以很简单快速的把VFR视频转换成CFR的:
```
ffmpeg -i input.mp4 -c:v hevc_videotoolbox -tag:v hvc1 -b:v 2M  -maxrate 2M -r 60 output.mp4
```
里面的`2M`就是码率, `60`是帧率
上面一条是转换H265格式的命令, H264可以用如下命令:
```
ffmpeg -i input.mp4 -c:v h264_videotoolbox -b:v 2M  -maxrate 2M -r 60 output.mp4
```

**Comment by lihaoyun6** [comment]
<img width="120" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/55edd16c-e089-4671-9f14-530afe44c0d0">

如果不会使用命令行的话, 也可以用 `HandBreak` 这种开源免费的图形化APP来转码

**Comment by powersee** [comment]
好的好的，我记下来了，非常感谢大佬。

**Comment by AndrewKeYanzhe** [comment]
> 这里显示的其实是"平均帧率", 因为QuickRecorder在写入文件的过程中是不会对长时间的静态画面重复写入相同帧的. 比如如果遇到画面保持静止不动的情况, QuickRecorder会停止实际的帧写入, 转而靠修改PTS时间码来保证视频同步. 你可以试一下: 录制一段静止画面, 和录制一段动态画面(比如网页视频). 最终录制出来的文件显示的平均帧率是不同的 这样可以更大限度的压缩文件体积, 并且不会影响视频播放. 在画面发生变化的时候, 确实是按照你设定的60fps进行录制的.

May I ask, how is this implemented? Does ScreenCaptureKit give duplicate frames to QuickRecorder, and then QuickRecorder checks if it is a duplicate? Or is ScreenCaptureKit configured to only give unique frames to QuickRecorder? I am interested in tweaking this behaviour for my fork (I notice that 4K60 recording will drop some frames, so I am trying to find a solutioin.
