### ISSUE TITLE
录制选择多个，录制下来的视频就全是黑屏

### ISSUE THREAD

**Issue by velentZ** [lihaoyun6/QuickRecorder#2]
#### 环境以及设备：
![image](https://github.com/lihaoyun6/QuickRecorder/assets/167523142/82fde95b-b84c-43a5-8566-185c20b1e8e2)
#### 复现步骤：
- 录制窗口内容
- 选择两个窗口一起录制
- 产出录屏，全黑

#### 期望：
- 这里支持多选的目的是画面自动合成吗？

**Comment by lihaoyun6** [comment]
非常抱歉给你的使用带来了不便, 目前情况是这样的:

1. 我本身使用的是Apple Silicon处理器的Mac, 并且手里已经没有基于intel的Mac了
2. 在我这边 (以及其他一些同样使用Apple Silicon Mac的用户) 多窗口录制功能是可以正常工作的

> 选择多个窗口之后会以屏幕区域为范围记录这几个窗口的画面, 和在显示器上看到的画面是一样的  

关于你遇到的问题, 我可能需要去借一台intel Mac进行调试, 来试着确定到底发生了什么.  

不过在此之前你可以尝试包括但不限于: `重启Mac`, `重启QuickRecorder`, `彻底卸载并重新安装QuickRecoreder`等操作看看有没有效果

**Comment by lamuyang** [comment]
I use an Intel Mac as well, but I cannot reproduce the bug mentioned above.
