### ISSUE TITLE
希望使用Applite下载和管理您的一些小工具

### ISSUE THREAD

**Issue by Mosaic-c** [lihaoyun6/QuickRecorder#20]
# 希望使用Applite下载和管理您的软件
## 缘由
你好，我最近使用了一个 Homebrew 的包管理器 [Applite](https://github.com/milanvarady/Applite)，在 Applite 中无法搜到您的小工具。Applite 的 [FAQ](https://aerolite.dev/applite/FAQ.html) 中介绍只要在 Homebrew Catalog 的都可以搜索到。
## 期望功能
如果方便的话，希望您的小工具都能加入到 Homebrew Catalog  🙇🏻‍♀️🙇🏻🙇🏻‍♂️

<img width="1082" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/33838624/bd0ed64f-1c6d-4e05-a791-bf65253871cd">

**Comment by lihaoyun6** [comment]
很抱歉, 暂时做不到. 并不是我不想往 Homebrew-Cask 仓库提交 QuickRecorder, 而是 brew 官方对所有提交的仓库都有一条硬性规定"仓库建立至少30天以上".
目前距离我创建这个仓库才15天, 即使提交给brew, 他们也不会通过审核. 所以请先耐心等待一段时间吧

**Comment by Mosaic-c** [comment]
嘿嘿，理解啦，后续您的其他工具如[AirBattery](https://github.com/lihaoyun6/AirBattery)也可以提交吗？

**Comment by Mosaic-c** [comment]
嘿嘿，理解啦，后续您的其他工具如[AirBattery](https://github.com/lihaoyun6/AirBattery)也可以提交吗？
~~哎呀不小心关单了~~
