### ISSUE TITLE
建议增加一个自定义窗口跟随鼠标移动的功能

### ISSUE THREAD

**Issue by shixueaaa811001** [lihaoyun6/QuickRecorder#21]
比如我要为录制9：16的窗口，录制的窗口可以跟随鼠标移动。录完视频，可以直接在手机播放

**Comment by shixueaaa811001** [comment]
> 至少

有人做，但做的不好。

**Comment by lihaoyun6** [comment]
> > 至少
> 
> 有人做，但做的不好。

你说的应该是类似Screen Studio的那个"Zoom"功能吧. 我看了一下, 他那个功能实际上是后期编辑的一部分, 而不是在录制的时候就直接变换录制区域.
他那个功能涉及到鼠标位置的记录, 点击动作的分析, 还要和视频时间轴做好同步. 最关键的是他是一个"后期编辑"功能, 是需要集成类似ffmpeg之类的剪辑工具的.
我不太想做(说句实在话也怕做不好)后期功能集. QuickRecorder目前只专注于前期录制

**Comment by lihaoyun6** [comment]
其实我前几天自己试了一下, 可以实现. 但是有几个很大的问题
1. 如果在录制过程中实现视口移动, 那后期就没有任何后悔的余地了, 因为视口外的内容根本就没录到, 万一没录全是找不回来的
2. 真人在使用鼠标的过程中其实鼠标抖动非常厉害, 只不过我们自己感觉不到. 但是录制到视频上就非常明显了, 鼠标的轻微颤动都会导致视口变换. 而平滑鼠标路径又会导致视口移动产生延迟
3. 真不是什么人都能适应鼠标极速移动的"甩狙视角"的, 我自己看了都晕
