### ISSUE TITLE
不知道咋停止录制，找到文件

### ISSUE THREAD

**Issue by aohanhongzhi** [lihaoyun6/QuickRecorder#22]
<img width="927" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/37319319/d219fd41-6ed3-4865-b60c-02df4fdcf777">

<img width="780" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/37319319/d7b22eb6-5bde-4d97-8277-399e8894e0a3">

<img width="780" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/37319319/2d8da648-b9b6-4bdd-a0a5-2f608ef690e9">

<img width="785" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/37319319/381d359c-ec28-4cc7-8376-d9816e3949a4">

<img width="551" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/37319319/f7fd88ca-4de4-4dbf-bd69-28989dcb7ad5">

录制后，然后就不知道咋找到界面操作停止录制了。

**Comment by lihaoyun6** [comment]
<img width="94" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/59cc2f9f-6261-48c8-981d-0a9dba503c63">
选择需要录制的内容之后, 要点击start开始录制

**Comment by lihaoyun6** [comment]
开始录制之后, QuickRecorder会自动隐藏内容选择器和主面板, 并在菜单栏上显示录制指示器和摄像头开关按钮

**Comment by aohanhongzhi** [comment]
> <img alt="image" width="94" src="https://private-user-images.githubusercontent.com/16348097/328022315-59cc2f9f-6261-48c8-981d-0a9dba503c63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTgyNTAsIm5iZiI6MTcxNDkxNzk1MCwicGF0aCI6Ii8xNjM0ODA5Ny8zMjgwMjIzMTUtNTljYzJmOWYtNjI2MS00OGM4LTk4MWQtMGE5ZGJhNTAzYzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE0MDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNjM0NTlmYzdmYmI4MDkzY2Q5ZmI3OTA4Nzg1NGI2ZTdkYjYxNTI2Mzc0ZjAxOTZhY2VkZGRiNGEwMmMwNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qc5vJ3-iD6skbdHB2Xvx25oQXMtwI0Z4UTbqYk74c0M"> 选择需要录制的内容之后, 要点击start开始录制

点了，然后自动隐藏了主界面。

**Comment by aohanhongzhi** [comment]
> 开始录制之后, QuickRecorder会自动隐藏内容选择器和主面板, 并在菜单栏上显示录制指示器和摄像头开关按钮
隐藏后就找不到了。

**Comment by lihaoyun6** [comment]
请提供一下更多有效信息, 比如: 系统版本, QuickRecorder版本, 出现问题时使用的录制模式, 有没有其他异常现象等...

**Comment by lihaoyun6** [comment]
也可以先自行尝试用以下方法获得更多运行时日志:
1. 打开系统自带的`终端`App, 并将下列命令复制粘贴到终端窗口内并按回车执行
 ```
/Applications/QuickRecorder.app/Contents/MacOS/QuickRecorder
```
2. 根据提示授予终端录屏权限
3. 授权后再次执行上面的命令
4. 操作录屏, 尝试复现问题
5. 把出现问题时终端窗口内显示的日志文本复制粘贴发上来

**Comment by lihaoyun6** [comment]
如果需要解决问题, 请尽快附上所需的信息以及日志, 如果不需要修复, 请主动关闭此issue. 不要"问后不理", 很浪费时间

**Comment by aohanhongzhi** [comment]
> 如果需要解决问题, 请尽快附上所需的信息以及日志, 如果不需要修复, 请主动关闭此issue. 不要"问后不理", 很浪费时间

目前还没有时间处理这个，调试，找日志。要上班呀，如果你觉得很浪费时间，那你就关闭吧。

**Comment by lihaoyun6** [comment]
> > 如果需要解决问题, 请尽快附上所需的信息以及日志, 如果不需要修复, 请主动关闭此issue. 不要"问后不理", 很浪费时间
> 
> 目前还没有时间处理这个，调试，找日志。要上班呀，如果你觉得很浪费时间，那你就关闭吧。

按照上面的方法, 复现一下bug, 复制粘贴一下日志, 五分钟都用不上好吧

**Comment by lihaoyun6** [comment]
怎么感觉倒过来了?
你来找我修复bug, 我上赶着每隔半小时刷新一次看看你会没回复我
然后你问完了就跑把我晾在一边?

**Comment by lihaoyun6** [comment]
抱歉刚刚有点焦躁。
我相信我们的目的是相同的，都是为了解决问题，让这个APP变得更好用，希望不要因为工作时间差原因导致彼此产生什么不好的误会。
烦请您在有时间的时候尽量帮忙收集一下报错日志，也方便我好尽快的解决问题。
谢谢

**Comment by aohanhongzhi** [comment]
@lihaoyun6  没事。

执行之后是这样的，日志也没有啥异常。

<img width="733" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/37319319/732806c3-5e7b-443a-9a79-e17a3983d0aa">

**Comment by lihaoyun6** [comment]
> @lihaoyun6 没事。
> 
> 执行之后是这样的，日志也没有啥异常。

用这种方法启动之后, 有尝试进行一次录屏吗? (为了触发bug)
理论上在启动录屏之后, 应该才会输出真正有用的日志信息

**Comment by lihaoyun6** [comment]
另外我看上面的屏幕截图显示, 你的笔记本应该是带刘海的款式吧
如果是这样的话, 还有一种可能性: 因为状态栏上的图标太多了, 导致没有多余的空间显示`录制指示器`, 也就是它被系统自动隐藏了. 可以尝试关掉状态栏上的一些app, 留出一点剩余空间再试试

**Comment by lihaoyun6** [comment]
![ce7cdeea2fd394c7e37f2d42523a628c](https://github.com/lihaoyun6/QuickRecorder/assets/16348097/5a297109-8f39-4737-a161-931a18199c21)
最近确实有一些用户遇到了"菜单栏图标太多导致QuickRecorder录制控制器显示不出来"的问题, 我打算在下个版本中加入对菜单栏图标的自动检测, 一旦检测到菜单栏图标无法正常显示, 就会弹出悬浮窗形态的录制控制器

**Comment by lihaoyun6** [comment]
长时间未得到回复, 故关闭此issue
