### ISSUE TITLE
录制的mp4文件 无法打开

### ISSUE THREAD

**Issue by lucktoo** [lihaoyun6/QuickRecorder#23]
<img width="687" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/23254843/35b5ac8c-7e63-4b40-a811-dfaee5c4d4eb">

**Comment by lihaoyun6** [comment]
是否在录制过程中使用了"演讲者前置"功能?  
如果使用"演讲者前置"的大形视图导致录制文件损坏的话, 请尝试在偏好设置中调大"演讲者前置延迟"的数值, 直到录像文件不会损坏

**Comment by lihaoyun6** [comment]
如果没有使用"演讲者前置"就出现了这种录屏文件损坏的情况, 请提供更多信息(比如QuickRecorder版本, 系统版本, 出现问题时使用的录制模式等...)

**Comment by lihaoyun6** [comment]
如果需要解决问题, 请尽快附上所需的信息以及日志, 如果不需要修复, 请主动关闭此issue. 不要"问后不理", 很浪费时间
难道我是神仙吗? 你随便几个字, 一张截图, 我就能知道哪里出了bug并把它修好?

**Comment by lihaoyun6** [comment]
来来来, 能不能行了? 是我求着你来报bug的吗? 问完了就跑, 你是把我当成许愿池里的王八了吗?

**Comment by quoyi** [comment]
一样的问题：录制完无法打开文件。

System Version: macOS 12.7.3 (21H1015)
Kernel Version: Darwin 21.6.0

**Comment by quoyi** [comment]
> > > 来来来, 能不能行了? 是我求着你来报bug的吗? 问完了就跑, 你是把我当成许愿池里的王八了吗?
> > 
> > 
> > 可能没有看 Email 习惯吧，淡定些。
> > 我也遇到这个问题，下面是机器和系统信息，还有 log 文件，希望有所帮助。
> > System Version: macOS 12.7.3 (21H1015) Kernel Version: Darwin 21.6.0
> > [QuickRecorder-2024-05-06-182852.log](https://github.com/lihaoyun6/QuickRecorder/files/15219537/QuickRecorder-2024-05-06-182852.log)
> 
> 看起来你应该是遇到崩溃闪退问题了吧. 建议通过下列方式运行QuickRecorder并复现bug以获得更详细的报错信息
> 
> 1. 打开系统自带的`终端`App, 并将下列命令复制粘贴到终端窗口内并按回车执行
> 
> ```
> /Applications/QuickRecorder.app/Contents/MacOS/QuickRecorder
> ```
> 
> 2. 根据提示授予终端录屏权限
> 3. 授权后再次执行上面的命令
> 4. 操作录屏, 尝试复现问题
> 5. 把出现问题时终端窗口内显示的日志文本复制粘贴发上来

是权限问题，已经配置了录屏权限，在 terminal 中运行时提示 `Notification authorization denied: Notifications are not allowed for this application`

**Comment by lihaoyun6** [comment]
感觉还是权限问题, 建议彻底卸载并重启Mac, 然后重新安装并授权试试

**Comment by lihaoyun6** [comment]
长时间未得到回复, 故关闭此issue

**Comment by wallleap** [comment]
@lihaoyun6 大佬，如果因为内存问题崩溃了，录制的文件还在，但是打不开，有没有办法让它能够播放哇
