### ISSUE TITLE
大佬，macOS 12.7 录制界面字体模糊发虚，控件貌似未对齐。

### ISSUE THREAD

**Issue by v5tech** [lihaoyun6/QuickRecorder#25]
首先，非常感谢大佬没有放弃macOS 12.X 老用户。

![image](https://github.com/lihaoyun6/QuickRecorder/assets/887836/46e0bc29-2ad7-4aca-a17e-42617d58a608)

设备分辨率信息

![image](https://github.com/lihaoyun6/QuickRecorder/assets/887836/fec4770a-6999-4269-9502-9882a162e462)

**Comment by lihaoyun6** [comment]
好的, 已收到反馈, 我会检查并尽量修复. 请耐心等待后续

**Comment by v5tech** [comment]
> 好的, 已收到反馈, 我会检查并尽量修复. 请耐心等待后续

辛苦大佬。

**Comment by lihaoyun6** [comment]
v1.1.7版本已发布, 修复了macOS 12系统以及非Retina显示器上的界面bug

**Comment by v5tech** [comment]
![image](https://github.com/lihaoyun6/QuickRecorder/assets/887836/4bc02164-0761-4cc4-95ec-573f38f792ce)

大佬确实高效，舒服多了。
