### ISSUE TITLE
录制屏幕区域一直存在一个 bug

### ISSUE THREAD

**Issue by sogoo** [lihaoyun6/QuickRecorder#26]
录制屏幕区域，在一个显示屏选定区域后，录制控件面板在另一个显示屏里，
录制的结果就不是选定的区域，而是会跟录制控件面板同屏。

**Comment by lihaoyun6** [comment]
好的, 已收到反馈, 会进行排查修复, 请耐心等待后续

**Comment by lihaoyun6** [comment]
已在v1.1.8版本中修复了此问题
