### ISSUE TITLE
macos 12.7.4 录屏mp4 使用默认输出到桌面 无输出文件

### ISSUE THREAD

**Issue by lvtao-net** [lihaoyun6/QuickRecorder#28]
使用的默认配置，输出到桌面，开始的时候是桌面上的文件有，但只有几百kb，并且mp4文件不能打开

然后又试了几次录制，有两次成功

我以为OK了，结果就录制了一个长达半小时候左右的操作。。。。然后结束后，，，，等了n久桌面上没有文件产出

于是我将配置中的h264调整为265，文件格式也改为了mov，30分钟操作后。。。依旧没有任何输出。。。。就很无奈.

 另外，本地已经brew安装了最新 的ffmpeg

**Comment by lihaoyun6** [comment]
首先对您的遭遇表示抱歉, 希望没有耽误正事.
其实一开始 QuickRecorder 是不打算支持 macOS 12 的, 因为苹果在 macOS 12-14 期间对 ScreenCapture Kit API 进行过大刀阔斧的改动. 基本上 12 系统的是一套, 13-14 系统的是另一套玩法, 很多部分是不互相兼容的...  
兼容 macOS 12 只是因为大家的呼声比较高, 所以勉强为之, 我确实不太想在"适配老系统"这方面投入太多精力. **所以我会尽量尝试修复您发现的bug, 但不能保证一定可以解决**

**Comment by shixueaaa811001** [comment]
12.7.4,录全屏，打不开录制的视频

**Comment by lihaoyun6** [comment]
> 12.7.4,录全屏，打不开录制的视频

可以试试按照上面给出的方法抓一下日志吗？谢谢

**Comment by lihaoyun6** [comment]
> 12.7.4,录全屏，打不开录制的视频

您好, 如果需要解决问题, 请尽快附上详细的日志信息. 不要"问后不理".... 我不是神仙, 你不给我日志我什么也解决不了

**Comment by lihaoyun6** [comment]
> 使用的默认配置，输出到桌面，开始的时候是桌面上的文件有，但只有几百kb，并且mp4文件不能打开
> 
> 然后又试了几次录制，有两次成功
> 
> 我以为OK了，结果就录制了一个长达半小时候左右的操作。。。。然后结束后，，，，等了n久桌面上没有文件产出
> 
> 于是我将配置中的h264调整为265，文件格式也改为了mov，30分钟操作后。。。依旧没有任何输出。。。。就很无奈.
> 
> 另外，本地已经brew安装了最新 的ffmpeg

距离您提交此issue并收到我"恳请帮忙抓去日志"的回复已经过去接近20小时, 如果您始终保持沉默, 我将在3个小时后关闭此issue, 并且不再接受您提交的同类型issue, 请好自为之.

**Comment by lihaoyun6** [comment]
经测试, 此问题是macOS 12.7.4系统本身的bug所致. 升级到macOS 12.7.4即可解决.
