### ISSUE TITLE
连接外接屏幕的情况下，录制屏幕区域没法跨屏幕拖动

### ISSUE THREAD

**Issue by fengkx** [lihaoyun6/QuickRecorder#3]
连接外接屏幕的情况下，录制屏幕区域没法跨屏幕拖动。无法把录制区域的框框从一个屏幕拖到另一个屏幕。

**Comment by lihaoyun6** [comment]
因为系统API不支持跨两个屏幕各录一部分区域, 所以QuickRecorder的默认逻辑是:
> 你在哪个显示器上点开录屏界面, 选择框就会被限定在哪个屏幕的区域范围中

所以想要录制其他屏幕非常简单: 只需要在你想录制的那个显示器上启动录屏就好了 (先把软件的主面板条拖过去, 然后再那台显示器上点击"屏幕区域录制")

**Comment by fengkx** [comment]
quicktime player 的录屏可以跨屏幕拖动
