### ISSUE TITLE
双显示器使用按应用程序录制，当QuickRecorder界面和所录制应用界面不在同一显示器时，录制失败

### ISSUE THREAD

**Issue by wodeguaiguai** [lihaoyun6/QuickRecorder#33]
MAC OS 14.4.1 (23E224)
Apple M2
双显示器

**Comment by lihaoyun6** [comment]
好的, 我排查一下

**Comment by wodeguaiguai** [comment]
1

**Comment by lihaoyun6** [comment]
<img width="390" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/92419ba6-4c83-441a-bcb0-f0d176014cfb">
因为ScreenCapture Kit API本身就没用提供"跨屏幕录制"的能力, 所以做不到同时录制多台显示器上的多个应用或多个窗口.  
不过新版QuickRecorder会为多显示器用户进行优化, 将内容选择器界面进行更新, 以帮助用户更好的区分位于不同显示器的内容, 避免出现跨显示器选择的情况. 
敬请期待

**Comment by lihaoyun6** [comment]
v1.2.0版本已经正式发布, 为`窗口选择器`和`App选择器`添加了多屏支持. 仅允许用户选择位于同一屏幕空间的内容, 杜绝了跨屏选取导致的录制失败.
