### ISSUE TITLE
英语界面的部分问题

### ISSUE THREAD

**Issue by huanqiugame** [lihaoyun6/QuickRecorder#36]
首先感谢作者的分享！

我的Mac现在设置为英文，所以App界面也是英文的。英文语言下，录制界面有一处翻译为Definition，直译后知道是清晰度的意思，但实际效果是更改分辨率。我认为改成Resolution会更明了一些？

![image](https://github.com/lihaoyun6/QuickRecorder/assets/85951426/910e4c85-26e0-4e78-b573-2c250ae58f3d)

此外，在13英寸的M2 MacBook Air（系统设置分辨率为默认）上，设置页的Select save folder按钮有超出部分变成省略号了，看看是否有方案解决。

![image](https://github.com/lihaoyun6/QuickRecorder/assets/85951426/4f8b5c19-7778-469f-825a-1988c52463e7)

<del>每次提issue都很正式，但又觉得不适合在B站直接发问……</del>

**Comment by lihaoyun6** [comment]
好的, 已收到反馈, 会在下个版本中集中修复

**Comment by lihaoyun6** [comment]
v1.2.1版本已发布, 修复了英文环境下部分界面文本显示不全, 以及文本描述不准确的问题, 请尝试更新看看.
如果更新后问题已被解决, 别忘记关闭此issue

**Comment by huanqiugame** [comment]
还没能通过Homebrew更新，可能是我镜像源的问题。直接下载的版本已修改，赞👍😄

**Comment by lihaoyun6** [comment]
> 还没能通过Homebrew更新，可能是我镜像源的问题。直接下载的版本已修改，赞👍😄

QuickRecorder从v1.1.4版本开始就内置了更新功能, 直接在App内检测更新就可以了
