### ISSUE TITLE
建议增加定时录制功能

### ISSUE THREAD

**Issue by oyeaono** [lihaoyun6/QuickRecorder#38]
可以指定录制结束的时间或者录制的时常，自动完成录制

**Comment by lihaoyun6** [comment]
<img width="249" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/5de25f97-5ed9-4605-b68b-8be333d82416">

此功能已在v1.2.3版本中实装  
在任意内容选择器界面点击开始录制按钮旁蓝色的计时器图标, 即可设置倒计时结束 (0为不自动结束)
