### ISSUE TITLE
应该录制的时候切换应用会同时被录进视频

### ISSUE THREAD

**Issue by lvtao-net** [lihaoyun6/QuickRecorder#39]
macOS 14.3 中， 录制视频选择应用。
然后我用 command+tab切换应用后，这个切换的列表会被录制进去！

切换完成后，即正常。 只有那一排列表会出现.

**Comment by lihaoyun6** [comment]
如果不想看到这个东西出现在视频里, 可以在选择录制内容的时候, 将"画面背景"选项改成除了"桌面背景"以外的任何颜色, 就可以不录制应用切换器了  

这个确实没有特别好的解决办法, 因为"录制桌面背景"功能是的原理是将Dock添加到录制列表中, 但是录制dock肯定就会把这个应用切换器给录到.
