### ISSUE TITLE
输出质量会对视频的什么方面产生影响？

### ISSUE THREAD

**Issue by Mobiusium** [lihaoyun6/QuickRecorder#42]
输出质量会对视频的什么方面产生影响？录制下载感觉对比不明显，视频的大小也没有太多差别。

**Comment by lihaoyun6** [comment]
输出质量选项控制着一个倍率因子, 用来调节最终的目标输出码率. 
高画质对应1.0, 中画质对应0.7, 低画质对应0.3. 但这是一种相对关系的控制, 并不绝对.
最终输出的实际码率还是要由多个条件综合计算得出的.

对于分辨率越大, 目标帧率越大的视频, 输出画质选项的效果差异越大
对于分辨率越小, 目标帧率越少的视频, 输出画质选项的效果差异越不明显

**Comment by lihaoyun6** [comment]
<img width="443" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/7ae1b5c0-d468-4159-b124-c27616805054">

比如同样都是分辨率3456 × 2234, 目标帧率60FPS, 相同时长, 相似画面内容的录屏, 低中高画质录制出来的文件大小就会产生明显区别
