### ISSUE TITLE
请问有可能支持macos12吗？

### ISSUE THREAD

**Issue by AlanDinkle** [lihaoyun6/QuickRecorder#5]
不是特别喜欢升级系统，如果这对你来说很麻烦那么就算啦

**Comment by lihaoyun6** [comment]
QuickRecorder 所使用的苹果 ScreenCapture Kit 最低支持的 macOS 版本是 12.3  
但是因为这个新 API 这几年经历了好几次大改, 导致旧版 macOS 上的 API 和新系统上的差别有点大  
如果强行要兼容的话, 就必须在低版本系统上舍弃掉一部分功能(比如内录系统声音), 还需要重写不少代码

作为一个纯兴趣驱动的业余开发者, 真的没有特别大的动力去做这件事, 抱歉😭

**Comment by lihaoyun6** [comment]
预计在1.0.7版本中将系统兼容性向下拓展至"macOS 12.3及以上系统"

**Comment by lihaoyun6** [comment]
> 如果对你来说很麻烦而且没意义的话，就算啦，在这个系统的人可能不会很多

实验性支持, 给老系统用户一条活路. 我不会对macOS 12上运行的QuickRecorder遇到的问题投入过多的精力去修复, 但是我会把能带到macOS 12的所有基础功能都下放下去.

**Comment by lihaoyun6** [comment]
**最新版 [v1.0.7](https://github.com/lihaoyun6/QuickRecorder/releases/tag/1.0.7) 已发布, 系统要求降低至 `macOS 12.3` 或更高**  

但是在 `macOS 12` 系统中, 下列功能特性不可用:
- 仅录制系统声音
- 应用/窗口声音内录
- 自定义录制帧速率
- 控制是否录制菜单栏
- 背景颜色(部分颜色可能无法正常显示)

**Comment by lihaoyun6** [comment]
现在 v1.0.8 版本允许 macOS 12 用户自定义录制帧率了
