### ISSUE TITLE
FeatureRequest: stream to fMP4

### ISSUE THREAD

**Issue by gchilds** [lihaoyun6/QuickRecorder#50]
with multiple audio channels included (no mixing)

**Comment by lihaoyun6** [comment]
<img width="289" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/420601dc-35c5-4f33-a6b6-48c2211a7291">

You can turn this off. 
This will allow QuickRecorder to write system sound and microphone input to separate audio tracks.

**Comment by gchilds** [comment]
More than no mixing, I'm interested in stream ability, which fMP4 gives you.

**Comment by lihaoyun6** [comment]
It seems that macOS's support for fMP4 is not perfect🧐 
OK, I will add it to the todo list, but it will not be implemented in the short term.
