### ISSUE TITLE
FeatureRequest: Save captured video as animated image (gif/png)

### ISSUE THREAD

**Issue by bykka** [lihaoyun6/QuickRecorder#54]
Not all bug report systems allow users to post a video or understand how to play an uploaded video.
In such cases, an animated image is a better choice.

**Comment by thevolcanomanishere** [comment]
@bykka You should use something like Handbrake to convert the output to whatever you want.

**Comment by lihaoyun6** [comment]
> Not all bug report systems allow users to post a video or understand how to play an uploaded video. In such cases, an animated image is a better choice.

<img width="100" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/feb08c2e-d8d4-4208-8d4d-250ecc1259a0">

I recommend you to use "Gifski" to export gifs. It's really great!

**Comment by phuclv90** [comment]
Gifski doesn't support PNG yet, I've created this request https://github.com/sindresorhus/Gifski/issues/343
But why is it closed as "completed"? It should be not implemented or something like that
