### ISSUE TITLE
Keep the screen area layout over sessions

### ISSUE THREAD

**Issue by darth-developer** [lihaoyun6/QuickRecorder#56]
# Current behavior
If you want to record a screen area, the rectangle for the area to be recorded shows up (with default size and at a default position). The user has to drag the area to the desired position and size.
If the recording session is finished and the user wants to start another session, the rectangle shows up again - the size and position of the rectangle is reset -> the user has to adjust it again.

# Desired behavior
The rectangle of the screen area to be recorded should remember the last layout (size and position) - so the user can quickly start another session of the same area without the need to adjust the rectangle again and again.
Optionally there may be a setting "Keep/Remember screen area size", that the user can select to define that the screen area will keep the settings over different recording sessions (if it would not be implemented by default).

**Comment by lihaoyun6** [comment]
I think you are right, I will put it on my todo list ☺️

**Comment by lihaoyun6** [comment]
This feature has been implemented in v1.2.8!

**Comment by darth-developer** [comment]
Thanks a lot for that quick fix!! Keep going, I like your product 😀

**Comment by lihaoyun6** [comment]
😄Thank u for the likes
