### ISSUE TITLE
录像文件随机保存失败

### ISSUE THREAD

**Issue by gml-sec** [lihaoyun6/QuickRecorder#57]
MacOS系统版本12.7.5，软件1.2.7最新版本，依然有概率录屏的文件保存失败（录屏文件0字节），而且暂停录屏后再开启录屏，录屏大概率会异常（录屏文件大小不会增加了，并且结束录屏后文件无法打开）。

**Comment by lihaoyun6** [comment]
> MacOS系统版本12.7.5，软件1.2.7最新版本，依然有概率录屏的文件保存失败（录屏文件0字节），而且暂停录屏后再开启录屏，录屏大概率会异常（录屏文件大小不会增加了，并且结束录屏后文件无法打开）。

macOS 12系统上出现的这种问题, 是由于苹果系统更新引入的新bug导致的. 从QuickRecorder软件角度尚无有效的修复手段.  
好比macOS是一间房子, 我是刮大白的, 如果房子地基出现了裂缝, 我刮再多大白上去也于事无补😢

**Comment by lihaoyun6** [comment]
作为极少数基于ScreenCapture Kit且支持macOS 12系统的录屏App. 我真的尽力了, 奈何苹果猪队友

**Comment by gml-sec** [comment]
好的，感谢
