### ISSUE TITLE
录制移动设备结束后，无法从底部栏中打开继续使用

### ISSUE THREAD

**Issue by zhaoshanchun** [lihaoyun6/QuickRecorder#59]
录制移动设备结束后，无法从底部栏中打开继续使用

**Comment by lihaoyun6** [comment]
我尝试了一下, 没有复现成功. 可否提供更多有效信息, 例如
系统版本, QuickRecorder版本, 以及更多录制过程中的操作复述

**Comment by lihaoyun6** [comment]
长时间未收到回复, 关闭此issue
