### ISSUE TITLE
是否增加录屏时同时录制摄像头的画面,类似screenity

### ISSUE THREAD

**Issue by answer24** [lihaoyun6/QuickRecorder#6]
在选择屏幕或窗口录制的情况下,可以增加同时录制摄像头的画面.
场景是做一些教程视频的时候,有摄像头画面+屏幕录制,效果会更好.
摄像头的画框大小可以调整和移动.
十分感谢. https://screenity.io/en/

**Comment by answer24** [comment]
🙏感谢,还是期待它可以上线.😊

**Comment by lihaoyun6** [comment]
> 🙏感谢,还是期待它可以上线.😊

这两天爆肝, 终于把"演讲者前置"给适配好了. 现在v1.1.0版本可以完整支持演讲者前置的各种用法. 你可以下载试一下
(演讲者前置功能需要macOS系统版本不低于14.2方可启用)

**Comment by answer24** [comment]
> > 🙏感谢,还是期待它可以上线.😊
> 
> 
> 
> 这两天爆肝, 终于把"演讲者前置"给适配好了. 现在v1.1.0版本可以完整支持演讲者前置的各种用法. 你可以下载试一下
> 
> (演讲者前置功能需要macOS系统版本不低于14.2方可启用)

👍🏻太棒了，过几天正好需要录视频，到时候体验后反馈，也会推荐给别人。

**Comment by lihaoyun6** [comment]
<img width="390" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/38a415ae-b95d-4426-9183-18a24f311f2a">

使用"演讲者前置"功能, 在选择录屏内容的时候, 就需要提前选好需要同步录制的摄像头

<img width="390" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/4c5521d5-d20b-425b-9b6e-468b293a170c">

然后在开始录屏之后, 可以从菜单栏上Sonoma系统自带的屏幕分享控制菜单里启用演讲者前置

**Comment by lihaoyun6** [comment]
另外如果在录制`全屏幕`/`屏幕区域`/`应用程序`/`多窗口`的情况下, 启用"小型演讲者前置视图"的话, 屏幕上显示的那个实时头像圈是可以随意拖动的. 拖动到你认为合适的位置就可以了

**Comment by lihaoyun6** [comment]
> QuickRecorder v1.1.1 更新日志:
    - 添加了 "演讲者前置延迟" 设置项, 如果启用 "大型" 视图导致录像损坏, 可尝试增大此值
    - ***添加了通用摄像头叠加功能, 可在不支持 "演讲者前置" 的系统上使用***
    - 添加了视频修剪器, 可以在结束录制后对录屏文件进行时间修剪
    - 修复了首次启动且使用录制全屏画面功能时壁纸变黑的问题

现在我又添加了一个通用版的摄像头叠加功能, 即使是不支持演讲者前置的老版本macOS也可以录屏同时录制摄像头了
