### ISSUE TITLE
窗口录制时，无法识别已经被打开的窗口，点击刷新也不行。

### ISSUE THREAD

**Issue by handbye** [lihaoyun6/QuickRecorder#60]
![image](https://github.com/lihaoyun6/QuickRecorder/assets/26617058/f834c282-d79c-4c5f-bd10-df7b78d29681)

**Comment by lihaoyun6** [comment]
额, 您上传的图片是gif吗? 但是在我这里看到是静态的. github可以直接传视频, 您可以传一下原始录像我看看

**Comment by lihaoyun6** [comment]
为了保证选择器的可用性, QuickRecorder默认会过滤掉一些特殊"窗口", 比如所有app的菜单栏图标, 某些无标题的空白隐藏窗口, 还有窗口标题为Window的默认窗体. 如果您发现您需要录制的窗口没有显示在选择器里, 可能是被过滤掉了.
可否提供更多相关信息, 比如具体是哪个App的哪个窗口不显示?

**Comment by lihaoyun6** [comment]
而且窗口选择器是根据显示器进行分类的, 如果您同时连接了多个显示器, 想要选择另一个显示器上的窗口, 需要先在选择器上切换到对应显示器的选项卡下才能看到

**Comment by handbye** [comment]
我已经切到第二显示器上了，还是啥都不显示

https://github.com/lihaoyun6/QuickRecorder/assets/26617058/d5c5d224-8767-4229-927b-189a5d2b42d5

另外的录屏软件是显示的
![image](https://github.com/lihaoyun6/QuickRecorder/assets/26617058/a2299172-4c42-45b0-bc05-31379a887531)

**Comment by lihaoyun6** [comment]
没能成功复现😢, 您有试过重启一下Mac吗

**Comment by handbye** [comment]
试过了，其实前面的版本就有这个问题。我觉得是因为这些窗口实在录屏工具之前打开的，所以无法识别，但不确定，有时候又是正常的。

**Comment by lihaoyun6** [comment]
应该不是这个原因. 窗口启动的先后顺序并不会影响识别, 即使是先于QuickRecorder启动的窗口也是可以正常录制的.
有没有试过只使用一块显示的时候能不能正常识别呢?

**Comment by lihaoyun6** [comment]
这是内置还是外置屏幕?

**Comment by handbye** [comment]
内置的

**Comment by handbye** [comment]
这里竟然遮挡了
![image](https://github.com/lihaoyun6/QuickRecorder/assets/26617058/15c97b19-9d9b-4d70-9fbf-fc412377bd4e)

**Comment by lihaoyun6** [comment]
我偶尔会遇到一种类似的情况, 但我不确定是不是你这种
就是ScreenCapture Kit API在某些情况下确实会卡住, 导致QuickRecorder无法在当前会话下获取任何屏幕上下文内容, 需要重启Mac才可以恢复
但你刚刚又说了重启是无效的...我就不太有把握了

**Comment by handbye** [comment]
我在重启下mac试试吧，反正这问题我遇到很多次了。就是不显示窗口，其它都正常。

**Comment by handbye** [comment]
我重启后，发现如下问题：
1. 不连接第二显示器，重启后窗口获取正常
2. HDMI插上第二显示器，窗口刷新后空白
3. 重启录屏软件，只能获取到第二显示器的窗口

我觉得是对外接显示器的支持有bug

**Comment by handbye** [comment]
> 我重启后，发现如下问题：
> 
> 1. 不连接第二显示器，重启后窗口获取正常
> 2. HDMI插上第二显示器，窗口刷新后空白
> 3. 重启录屏软件，只能获取到第二显示器的窗口
> 
> 我觉得是对外接显示器的支持有bug

连上外接显示器，刷新后窗口又成空白了。

**Comment by lihaoyun6** [comment]
[QuickRecorder.zip](https://github.com/lihaoyun6/QuickRecorder/files/15464414/QuickRecorder.zip)
我打包了一个测试版的app. 在使用窗口选择功能的时候会弹出包含调试信息的对话框, 你可以试着运行一下然后看看弹出了什么

**Comment by handbye** [comment]
![image](https://github.com/lihaoyun6/QuickRecorder/assets/26617058/60c79c53-885c-4cda-a0d4-b232471d0dd3)

**Comment by lihaoyun6** [comment]
我发现在启动两个QuickRecorder实例的时候会无法正常截取.
但是您的这个问题我真的没办法复现, 我这边也是多屏环境, 甚至是三屏幕(还包括一个随航iPad), 但是没有任何问题, 完全正常

**Comment by lihaoyun6** [comment]
而且这么多用户第一次有人提这个bug. 我更倾向于是您那边的使用方法或者macOS配置有问题, 而不是QuickRecorder的问题

**Comment by handbye** [comment]
好的，就是很奇怪, 我用其它录屏工具，比如omi录屏专家， 是没有这个问题的。

**Comment by lihaoyun6** [comment]
[QuickRecorder.zip](https://github.com/lihaoyun6/QuickRecorder/files/15466093/QuickRecorder.zip)

又修改了一个版本, 你先试试这个版本直接获取能不能获取到
<img width="424" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/475bc3f1-2ded-4488-b61e-a59a5689b6f5">

如果获取不到的话, 试试勾选这个"不创建缩略图", 然后刷新一下看看能不能获取到

**Comment by handbye** [comment]
你好，这个版本可以正常显示了
![image](https://github.com/lihaoyun6/QuickRecorder/assets/26617058/97344d0a-b584-49f9-99b3-ab7e4be25f48)

**Comment by lihaoyun6** [comment]
好的, 那我会把这项修复尽快合并到v1.2.9版本的更新中, 请留意软件更新提醒
