### ISSUE TITLE
能否增加“打开任意视频文件进行剪辑“的功能

### ISSUE THREAD

**Issue by monlite** [lihaoyun6/QuickRecorder#61]
录制完视频后自动打开的剪辑工具简单够用，这个功能很喜欢，不用安装其他的剪辑工具了。

但是目前好像只能录制视频结束自动弹出，仅能对当前录制的视频进行剪辑，如果当时只是想录制一些素材，没有来得及剪辑，后面想再剪辑就没法找到剪辑入口了。想问能否开放个独立入口给剪辑工具，增加“打开任意视频文件进行剪辑“的功能。

感谢作者！

**Comment by lihaoyun6** [comment]
其实是有这个功能的, 您右键点击视频文件, 选择使用QuickRecorder打开, 就会自动进入修剪器界面

**Comment by lihaoyun6** [comment]
<img width="514" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/b019279f-f775-402e-80b9-69ebbf36948f">
