### ISSUE TITLE
弹出的配置界面不是屏幕居中显示且不能移动，无法点击“Close”按钮

### ISSUE THREAD

**Issue by danny-su** [lihaoyun6/QuickRecorder#63]
弹出的配置界面不是屏幕居中显示且不能移动（需要移动变暗的Toolbar才能移动窗口，不够直观），无法点击“Close”按钮
<img width="1020" alt="QuickRecorder 2024-05-30 11 39 56" src="https://github.com/lihaoyun6/QuickRecorder/assets/12178855/f45db08b-cd3b-43c4-be08-2bddf14adc19">

**Comment by lihaoyun6** [comment]
因为这个面板实际上是一个sheet组件, 而不是一个窗口.   
你可以拖拽主窗口两侧或者顶上的这些"空白区域"来移动他. 或者直接按`Esc`来关闭设置面板
<img width="400" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/a974d204-a13f-40e1-a4e4-bd8ee302f06f">
