### ISSUE TITLE
感谢大佬，3点优化需求供参考

### ISSUE THREAD

**Issue by gavinweixin** [lihaoyun6/QuickRecorder#66]
大佬好，感谢开发这么好用的工具！我主要用在在线会议的录制，有几个需求供参考：

1）增加自定义文件名称功能：自定义YYMMDD和特定字符的文件名；
2）增加自定义码率功能，或者有没有什么设置可以减小录制文件的体积：在线会议不需要很高的码率但对分辨率要求还是高的，现在选择10FPS、输出“低画质”、清晰度选“高”（选择“中”的话就模糊了），1小时的录制下来文件体积还是偏大的；
3）减少麦克风串扰的优化：现在不开减少串扰会有明显的叠音，开了的话麦克风的收音会比较浑浊，可以考虑减少麦克风的音轨

感谢！

**Comment by lihaoyun6** [comment]
1. 我会考虑把自定义文件名这个需求添加到todo列表
2. 我这边录制2K分辨率的窗口(也是在线会议播PPT), "H265+15FPS+低画质+高清晰度". 1小时大概是370M~400M左右. 你是保存为H264还是H265?
3. 这个我还在捣鼓, 未来版本中可能会有优化

**Comment by gavinweixin** [comment]
2）刚刚试了一下H265，体积小很多了！但不知道为啥OBS默认的中体积视频，H264，体积还是更小（H264）
3）期待！
