### ISSUE TITLE
录制 不支持窗口切换？（实在没研究明白）

### ISSUE THREAD

**Issue by yangyang5214** [lihaoyun6/QuickRecorder#68]
比如 我在 chrome   finder terminal 多个 app直接进行切换，但是只会录制在 第一个窗口时候的视频？

**Comment by lihaoyun6** [comment]
"窗口"录制模式是针对特定窗口的, 只会录制你选中的窗口, 开始录制后此App新弹出来的窗口不会自动包含.
如果你需要录制一个或多个App的全部窗口, 且需要包含在录制过程中这些App弹出的任意新窗口, 请使用"应用"录制模式

**Comment by yangyang5214** [comment]
一样的。

假设我选择了三个

<img width="806" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/23392325/c81aeaab-1dac-4f18-b586-f5f895e22a4b">


但是实际录制也还是一个 APP的画面。

**Comment by lihaoyun6** [comment]
https://github.com/lihaoyun6/QuickRecorder/assets/16348097/0c9e1958-97fc-42b0-a096-fcee6f4b8c24

无法复现. 我这边录制多应用一切正常

**Comment by yangyang5214** [comment]
https://github.com/lihaoyun6/QuickRecorder/assets/23392325/fdb2eded-6bd3-4aac-80fd-ceefb43d829c

- 先进行了录制
- 后面进行了回放，可以看到之后  chrome 一个画面

**Comment by lihaoyun6** [comment]
系统版本, QuickRecorder版本分别都是多少呢

**Comment by yangyang5214** [comment]
- QuickTime Player

```
Version 10.5 (1154.4.2)
```

- Mac
 
```
Apple M2
macOS: 13.6.6 (22G630)
```

**Comment by lihaoyun6** [comment]
QuickRecorder版本, 不是QuickTime版本

**Comment by yangyang5214** [comment]
> QuickRecorder版本, 不是QuickTime版本

已更正

**Comment by lihaoyun6** [comment]
不行, 真没复现出来. 我特意装了个13.6.6的虚拟机和chrome还有google earth.
你有试过重启一下吗?

**Comment by yangyang5214** [comment]
> 已重启无效（和 google earth 没啥关系  任意软件切换都没用）


我发现 screen录制 网页跳转也没录制上 只会卡在第一个画面截图

**Comment by lihaoyun6** [comment]
建议通过下列方式运行QuickRecorder并尝试复现bug, 看看能不能获得更详细的报错信息:  
1. 打开系统自带的`终端`App, 并将下列命令复制粘贴到终端窗口内并按回车执行
 ```
/Applications/QuickRecorder.app/Contents/MacOS/QuickRecorder
```
2. 根据提示授予终端录屏权限
3. 授权后再次执行上面的命令
4. 操作录屏, 尝试复现问题
5. 把出现问题时终端窗口内显示的日志文本复制粘贴发上来

**Comment by yangyang5214** [comment]
mp4 视频格式设置的问题

MOV 正常

<img width="593" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/23392325/9d64cfd5-105b-46b9-b9f4-2a90a6af0cf5">
