### ISSUE TITLE
纯小白，请问安装好现实打不开该怎么操作

### ISSUE THREAD

**Issue by jiajianannianjing** [lihaoyun6/QuickRecorder#69]
<img width="258" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/171638438/2f78d195-d507-422d-be93-a0c6991ffe19">

**Comment by SevDaisy** [comment]
<img width="1116" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/44106157/eeac14e5-5168-4f01-a50e-70708ede43c0">
⌘ + 空格键，输入 安全性设置，鼠标点击打开。在安全性这里，改成我这样的选项。而且头一次打开软件，会多一个框，点选「仍然允许」就好了。

**Comment by jiajianannianjing** [comment]
￼安全性是打开的  但是打开软件还是这样显示  无法检查  需要软件更新。
2024年6月4日 15:15，章一砚 ***@***.***> 写道：

**Comment by ZaynTseng** [comment]
在 访达-应用程序 找到QuickRecorder，然后右键选择打开，就会弹出窗口让你确认是否打开了。

**Comment by jiajianannianjing** [comment]
十分感谢那么晚了还回复！早点休息。我明天来继续尝试。发自我的 iPhone在 2024年6月5日，23:27，ZaynTseng ***@***.***> 写道：﻿
在 访达-应用程序 找到QuickRecorder，然后右键选择打开，就会弹出窗口让你确认是否打开了。
