### ISSUE TITLE
录制系统音频崩溃

### ISSUE THREAD

**Issue by wang93wei** [lihaoyun6/QuickRecorder#7]
完整错误报告：
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QuickRecorder [1992]
Path:                  /Applications/QuickRecorder.app/Contents/MacOS/QuickRecorder
Identifier:            com.lihaoyun6.QuickRecorder
Version:               1.0.6 (105)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-04-26 09:18:52.9533 +0800
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        961470C7-9A53-FA41-75B4-BDD354AED784

Time Awake Since Boot: 490 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001afab8ee0

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [1992]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x1afab8ee0 _assertionFailure(_:_:file:line:flags:) + 268
1   libswiftCore.dylib            	       0x1afb26e74 swift_unexpectedError + 668
2   QuickRecorder                 	       0x102139aa8 specialized AppDelegate.prepareAudioRecording() + 984
3   QuickRecorder                 	       0x102134e10 AppDelegate.prepRecord(type:screens:windows:applications:) + 6608
4   QuickRecorder                 	       0x1021376e0 @objc AppDelegate.prepRecord(type:screens:windows:applications:) + 192
5   QuickRecorder                 	       0x102124c7c closure #1 in closure #1 in closure #1 in closure #1 in ContentView.body.getter + 124
6   SwiftUI                       	       0x1cce92ca4 0x1cb683000 + 25230500
7   SwiftUI                       	       0x1cc4c5690 0x1cb683000 + 14952080
8   SwiftUI                       	       0x1cc4c9608 0x1cb683000 + 14968328
9   SwiftUI                       	       0x1cc4c9554 0x1cb683000 + 14968148
10  SwiftUI                       	       0x1ccac9254 0x1cb683000 + 21258836
11  SwiftUI                       	       0x1cba51104 0x1cb683000 + 3989764
12  SwiftUI                       	       0x1cc5d8bc4 0x1cb683000 + 16079812
13  SwiftUI                       	       0x1cc66ad64 0x1cb683000 + 16678244
14  SwiftUI                       	       0x1cc5d8bc4 0x1cb683000 + 16079812
15  SwiftUI                       	       0x1cce8074c 0x1cb683000 + 25155404
16  SwiftUI                       	       0x1cce7fdc4 0x1cb683000 + 25152964
17  SwiftUI                       	       0x1cd0074a0 0x1cb683000 + 26756256
18  SwiftUI                       	       0x1cc3dea80 0x1cb683000 + 14006912
19  SwiftUI                       	       0x1cc3df054 0x1cb683000 + 14008404
20  SwiftUI                       	       0x1cc3e85f8 0x1cb683000 + 14046712
21  SwiftUI                       	       0x1cc3e841c 0x1cb683000 + 14046236
22  AppKit                        	       0x1a4235834 _routeMouseUpEvent + 132
23  AppKit                        	       0x1a3827f8c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 384
24  AppKit                        	       0x1a3827c38 -[NSWindow(NSEventRouting) sendEvent:] + 284
25  AppKit                        	       0x1a3eede70 -[NSApplication(NSEventRouting) sendEvent:] + 1604
26  AppKit                        	       0x1a3b3b8cc -[NSApplication _handleEvent:] + 60
27  AppKit                        	       0x1a36efcdc -[NSApplication run] + 512
28  AppKit                        	       0x1a36c6f54 NSApplicationMain + 880
29  SwiftUI                       	       0x1cb78d1e0 0x1cb683000 + 1090016
30  SwiftUI                       	       0x1cbef28ec 0x1cb683000 + 8845548
31  SwiftUI                       	       0x1cc2eca5c 0x1cb683000 + 13015644
32  QuickRecorder                 	       0x102149110 main + 64
33  dyld                          	       0x19fa3e0e0 start + 2360

Thread 1:
0   libsystem_pthread.dylib       	       0x19fdc1d20 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x19fdc1d20 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19fdc1d20 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x19fdc1d20 start_wqthread + 0

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x19fd861f4 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19fd98b24 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19fd8ee34 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x19fd86578 mach_msg + 24
4   CoreFoundation                	       0x19fea6058 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x19fea491c __CFRunLoopRun + 1208
6   CoreFoundation                	       0x19fea3e0c CFRunLoopRunSpecific + 608
7   AppKit                        	       0x1a3825cb4 _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x19fdc6f94 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x19fdc1d34 thread_start + 8

Thread 6:
0   libsystem_pthread.dylib       	       0x19fdc1d20 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x19fdc1d20 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000000013c444998   x1: 0x0000000200000003   x2: 0x000000013c500000   x3: 0x000000013c593400
    x4: 0x0000000000000110   x5: 0x000000013c593400   x6: 0x0000000000000012   x7: 0x0000000000000000
    x8: 0xfffffffe00000000   x9: 0x0000000200000003  x10: 0x0000000000000003  x11: 0x0000000000127480
   x12: 0x000000013c503f6c  x13: 0x0000000000000011  x14: 0x000000013c500000  x15: 0x00000000fffc7fff
   x16: 0xd79600010273c080  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x00000001aff9d9f4
   x20: 0x000000013c444990  x21: 0x0000000000000000  x22: 0x000000000000000b  x23: 0x0000000000000020
   x24: 0x00000000000000b0  x25: 0x000000010215e930  x26: 0xf0000000000000fc  x27: 0x0000000000000001
   x28: 0x0000000208147558   fp: 0x000000016dd022a0   lr: 0x00000001afab8ee0
    sp: 0x000000016dd021d0   pc: 0x00000001afab8ee0 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x11ac78000 -        0x11adaffff com.apple.audio.units.Components (1.14) <261ddb64-4aeb-3916-961f-46dad090dd47> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
       0x1026bc000 -        0x1026c7fff libobjc-trampolines.dylib (*) <e8a1b184-0349-3c61-a119-6543eb038317> /usr/lib/libobjc-trampolines.dylib
       0x1020fc000 -        0x102177fff com.lihaoyun6.QuickRecorder (1.0.6) <d9b47605-3fd3-3ed7-ba23-ad802f171017> /Applications/QuickRecorder.app/Contents/MacOS/QuickRecorder
       0x1afa7f000 -        0x1affdcfff libswiftCore.dylib (*) <05650d36-bbc5-3760-aec7-4d2751b5d729> /usr/lib/swift/libswiftCore.dylib
       0x1cb683000 -        0x1cd356fff com.apple.SwiftUI (5.4.38.401) <9cf47b50-8046-3dd2-942b-b165c0d98534> /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
       0x1a36c2000 -        0x1a49fefff com.apple.AppKit (6.9) <8b85317d-d56a-3370-8b78-da6c1d0fb53c> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x19fa38000 -        0x19fac09db dyld (*) <f6dd3ec2-85a4-3ab1-8486-b189cd980ebe> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x19fdc0000 -        0x19fdccfff libsystem_pthread.dylib (*) <45239f06-cc53-36d0-9933-7776ac7ea2fa> /usr/lib/system/libsystem_pthread.dylib
       0x19fd85000 -        0x19fdbfffb libsystem_kernel.dylib (*) <2a91fd2c-4cef-3211-a025-7a1c0a8c2db5> /usr/lib/system/libsystem_kernel.dylib
       0x19fe28000 -        0x1a0300fff com.apple.CoreFoundation (6.9) <33908a83-098f-3437-973e-fb848c4f39df> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)
Writable regions: Total=375.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=375.8M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
AttributeGraph Data               1024K        1 
CG image                           112K        6 
ColorSync                          576K       27 
CoreAnimation                     1552K       97 
CoreGraphics                        48K        3 
CoreGraphics (reserved)             48K        3         reserved VM address space (unallocated)
CoreServices                       624K        2 
CoreUI image data                 4304K       29 
Dispatch continuations            80.0M        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           281.4M       69 
MALLOC guard page                  288K       18 
STACK GUARD                       56.1M        8 
Stack                             11.7M        8 
VM_ALLOCATE                        256K       16 
__AUTH                            1489K      277 
__AUTH_CONST                      24.4M      464 
__CTF                               824        1 
__DATA                             9.8M      450 
__DATA_CONST                      23.0M      471 
__DATA_DIRTY                      1373K      152 
__FONT_DATA                          4K        1 
__LINKEDIT                       526.9M        4 
__OBJC_RO                         71.7M        1 
__OBJC_RW                         2195K        1 
__TEXT                           560.1M      488 
dyld private memory                272K        2 
mapped file                      297.2M       40 
shared memory                      896K       16 
===========                     =======  ======= 
TOTAL                              1.9G     2660 
TOTAL, minus reserved VM space     1.9G     2660 

-----------
Full Report
-----------

{"app_name":"QuickRecorder","timestamp":"2024-04-26 09:18:53.00 +0800","app_version":"1.0.6","slice_uuid":"d9b47605-3fd3-3ed7-ba23-ad802f171017","build_version":"105","platform":1,"bundleID":"com.lihaoyun6.QuickRecorder","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.4.1 (23E224)","roots_installed":0,"name":"QuickRecorder","incident_id":"8733E6A8-49A5-445E-815C-3B4E224DA80E"}
{
  "uptime" : 490,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 1472,
  "osVersion" : {
    "train" : "macOS 14.4.1",
    "build" : "23E224",
    "releaseType" : "User"
  },
  "captureTime" : "2024-04-26 09:18:52.9533 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "8733E6A8-49A5-445E-815C-3B4E224DA80E",
  "pid" : 1992,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-04-26 09:18:34.3254 +0800",
  "procStartAbsTime" : 11417329639,
  "procExitAbsTime" : 11863939524,
  "procName" : "QuickRecorder",
  "procPath" : "\/Applications\/QuickRecorder.app\/Contents\/MacOS\/QuickRecorder",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.6","CFBundleVersion":"105","CFBundleIdentifier":"com.lihaoyun6.QuickRecorder"},
  "storeInfo" : {"deviceIdentifierForVendor":"5547BF13-8FFB-55E3-8B8D-1B010585AD9F","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.lihaoyun6.QuickRecorder",
  "crashReporterKey" : "961470C7-9A53-FA41-75B4-BDD354AED784",
  "codeSigningID" : "com.lihaoyun6.QuickRecorder",
  "codeSigningTeamID" : "L4T783637F",
  "codeSigningFlags" : 1644245781,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"4gMZquMDF6rkAxWq5QMTquYDFqrnAxiqFQCA0pYDAJTgAxSqazQPlA==","atPC":"IAAg1CgAgFKJEoBS6BMAuekHAPlIAIBS6AMAOSAnALAA0CeRIycAsA=="},
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x00000001afab8ee0","rawCodes":[1,7242223328],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":1992},
  "os_fault" : {"process":"QuickRecorder"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":24489,"threadState":{"x":[{"value":5306075544},{"value":8589934595,"objc-selector":"BulkSendSessionInitiator"},{"value":5306843136},{"value":5307446272},{"value":272},{"value":5307446272},{"value":18},{"value":0},{"value":18446744065119617024},{"value":8589934595,"objc-selector":"BulkSendSessionInitiator"},{"value":3},{"value":1209472},{"value":5306859372},{"value":17},{"value":5306843136},{"value":4294737919},{"value":15534603968997212288},{"value":0},{"value":0},{"value":7247354356},{"value":5306075536},{"value":0},{"value":11},{"value":32},{"value":176},{"value":4329957680},{"value":17293822569102704892},{"value":1},{"value":8725493080,"symbolLocation":0,"symbol":"_swiftEmptyArrayStorage"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7242223328},"cpsr":{"value":1610616832},"fp":{"value":6137324192},"sp":{"value":6137323984},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":7242223328,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":237280,"symbol":"_assertionFailure(_:_:file:line:flags:)","symbolLocation":268,"imageIndex":3},{"imageOffset":687732,"symbol":"swift_unexpectedError","symbolLocation":668,"imageIndex":3},{"imageOffset":252584,"symbol":"specialized AppDelegate.prepareAudioRecording()","symbolLocation":984,"imageIndex":2},{"imageOffset":232976,"symbol":"AppDelegate.prepRecord(type:screens:windows:applications:)","symbolLocation":6608,"imageIndex":2},{"imageOffset":243424,"symbol":"@objc AppDelegate.prepRecord(type:screens:windows:applications:)","symbolLocation":192,"imageIndex":2},{"imageOffset":167036,"symbol":"closure #1 in closure #1 in closure #1 in closure #1 in ContentView.body.getter","symbolLocation":124,"imageIndex":2},{"imageOffset":25230500,"imageIndex":4},{"imageOffset":14952080,"imageIndex":4},{"imageOffset":14968328,"imageIndex":4},{"imageOffset":14968148,"imageIndex":4},{"imageOffset":21258836,"imageIndex":4},{"imageOffset":3989764,"imageIndex":4},{"imageOffset":16079812,"imageIndex":4},{"imageOffset":16678244,"imageIndex":4},{"imageOffset":16079812,"imageIndex":4},{"imageOffset":25155404,"imageIndex":4},{"imageOffset":25152964,"imageIndex":4},{"imageOffset":26756256,"imageIndex":4},{"imageOffset":14006912,"imageIndex":4},{"imageOffset":14008404,"imageIndex":4},{"imageOffset":14046712,"imageIndex":4},{"imageOffset":14046236,"imageIndex":4},{"imageOffset":12007476,"symbol":"_routeMouseUpEvent","symbolLocation":132,"imageIndex":5},{"imageOffset":1466252,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":384,"imageIndex":5},{"imageOffset":1465400,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":284,"imageIndex":5},{"imageOffset":8568432,"symbol":"-[NSApplication(NSEventRouting) sendEvent:]","symbolLocation":1604,"imageIndex":5},{"imageOffset":4692172,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":5},{"imageOffset":187612,"symbol":"-[NSApplication run]","symbolLocation":512,"imageIndex":5},{"imageOffset":20308,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":5},{"imageOffset":1090016,"imageIndex":4},{"imageOffset":8845548,"imageIndex":4},{"imageOffset":13015644,"imageIndex":4},{"imageOffset":315664,"symbol":"main","symbolLocation":64,"imageIndex":2},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":6}]},{"id":24490,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6137884672},{"value":3331},{"value":6137348096},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6137884672},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976970016},"far":{"value":0}}},{"id":24491,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6138458112},{"value":8195},{"value":6137921536},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6138458112},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976970016},"far":{"value":0}}},{"id":24492,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6139031552},{"value":18695},{"value":6138494976},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6139031552},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976970016},"far":{"value":0}}},{"id":24493,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6139604992},{"value":48915},{"value":6139068416},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6139604992},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976970016},"far":{"value":0}}},{"id":24498,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592,"objc-selector":"ingBulkSendSessionInitiator"},{"value":273791280218112},{"value":0},{"value":273791280218112},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":63747},{"value":0},{"value":1},{"value":63747},{"value":601849},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8890068496},{"value":0},{"value":4294967295},{"value":2},{"value":273791280218112},{"value":0},{"value":273791280218112},{"value":6140174440},{"value":8589934592,"objc-selector":"ingBulkSendSessionInitiator"},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6976801572},"cpsr":{"value":4096},"fp":{"value":6140174288},"sp":{"value":6140174208},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976725492},"far":{"value":0}},"frames":[{"imageOffset":4596,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":9},{"imageOffset":80676,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":9},{"imageOffset":40500,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":9},{"imageOffset":5496,"symbol":"mach_msg","symbolLocation":24,"imageIndex":9},{"imageOffset":516184,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":10},{"imageOffset":510236,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":10},{"imageOffset":507404,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":10},{"imageOffset":1457332,"symbol":"_NSEventThread","symbolLocation":144,"imageIndex":5},{"imageOffset":28564,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":8},{"imageOffset":7476,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":24499,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6140751872},{"value":61207},{"value":6140215296},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6140751872},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976970016},"far":{"value":0}}},{"id":24500,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6141325312},{"value":127499},{"value":6140788736},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6141325312},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6976970016},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4744249344,
    "CFBundleShortVersionString" : "1.14",
    "CFBundleIdentifier" : "com.apple.audio.units.Components",
    "size" : 1277952,
    "uuid" : "261ddb64-4aeb-3916-961f-46dad090dd47",
    "path" : "\/System\/Library\/Components\/CoreAudio.component\/Contents\/MacOS\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "1.14"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4335583232,
    "size" : 49152,
    "uuid" : "e8a1b184-0349-3c61-a119-6543eb038317",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4329553920,
    "CFBundleShortVersionString" : "1.0.6",
    "CFBundleIdentifier" : "com.lihaoyun6.QuickRecorder",
    "size" : 507904,
    "uuid" : "d9b47605-3fd3-3ed7-ba23-ad802f171017",
    "path" : "\/Applications\/QuickRecorder.app\/Contents\/MacOS\/QuickRecorder",
    "name" : "QuickRecorder",
    "CFBundleVersion" : "105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7241986048,
    "size" : 5627904,
    "uuid" : "05650d36-bbc5-3760-aec7-4d2751b5d729",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7707570176,
    "CFBundleShortVersionString" : "5.4.38.401",
    "CFBundleIdentifier" : "com.apple.SwiftUI",
    "size" : 30228480,
    "uuid" : "9cf47b50-8046-3dd2-942b-b165c0d98534",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/Versions\/A\/SwiftUI",
    "name" : "SwiftUI",
    "CFBundleVersion" : "5.4.38.401"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7036739584,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20172800,
    "uuid" : "8b85317d-d56a-3370-8b78-da6c1d0fb53c",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.50.124"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6973259776,
    "size" : 559580,
    "uuid" : "f6dd3ec2-85a4-3ab1-8486-b189cd980ebe",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6976962560,
    "size" : 53248,
    "uuid" : "45239f06-cc53-36d0-9933-7776ac7ea2fa",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6976720896,
    "size" : 241660,
    "uuid" : "2a91fd2c-4cef-3211-a025-7a1c0a8c2db5",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6977388544,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5083136,
    "uuid" : "33908a83-098f-3437-973e-fb848c4f39df",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2420"
  }
],
  "sharedCache" : {
  "base" : 6972506112,
  "size" : 4189880320,
  "uuid" : "a53b7d2f-a773-3524-8828-248b33ef0b4e"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=375.8M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=375.8M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nAttributeGraph Data               1024K        1 \nCG image                           112K        6 \nColorSync                          576K       27 \nCoreAnimation                     1552K       97 \nCoreGraphics                        48K        3 \nCoreGraphics (reserved)             48K        3         reserved VM address space (unallocated)\nCoreServices                       624K        2 \nCoreUI image data                 4304K       29 \nDispatch continuations            80.0M        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           281.4M       69 \nMALLOC guard page                  288K       18 \nSTACK GUARD                       56.1M        8 \nStack                             11.7M        8 \nVM_ALLOCATE                        256K       16 \n__AUTH                            1489K      277 \n__AUTH_CONST                      24.4M      464 \n__CTF                               824        1 \n__DATA                             9.8M      450 \n__DATA_CONST                      23.0M      471 \n__DATA_DIRTY                      1373K      152 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       526.9M        4 \n__OBJC_RO                         71.7M        1 \n__OBJC_RW                         2195K        1 \n__TEXT                           560.1M      488 \ndyld private memory                272K        2 \nmapped file                      297.2M       40 \nshared memory                      896K       16 \n===========                     =======  ======= \nTOTAL                              1.9G     2660 \nTOTAL, minus reserved VM space     1.9G     2660 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "125547681d13140e410d381b815747b61140b0c1",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "652eff3d1bce5442b8d753c9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000009
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a34d22a1-a1a5-4126-a477-0c499e502c6a",
      "experimentId" : "65835bc103dc58766bab2d27",
      "deploymentId" : 400000011
    }
  ]
}
}

Model: MacBookPro18,1, BootROM 10151.101.3, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Display: Q27P10, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Jan 20 2024 04:08:41 version 20.103.12.0.8.7.171 FWID 01-e09d2675
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: iPhone
USB Device: USB31Bus
USB Device: EarPods
USB Device: USB31Bus
USB Device: USB3.0 Hub
USB Device: USB2.0 Hub
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by lihaoyun6** [comment]
可以先试试换个录音格式, 然后看看是否还会闪退. 如果所有录音格式设置之后都会闪退的话, 那我可能就真的需要排错了
