### ISSUE TITLE
关于双屏多面手如何开启

### ISSUE THREAD

**Issue by King-hsw** [lihaoyun6/QuickRecorder#70]
<img width="1216" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/52289468/bdab2781-159a-459e-9dea-8b22743d4e1c">
QuickRecorder 可同时录制 Mac 和 iOS 设备，这个同时是指一个画面中即在录像mac又在录像ios吗？

**Comment by King-hsw** [comment]
我现在使用录制移动设备的话，仅仅只能录制手机的画面，没办法把电脑画面一起录制进去

**Comment by lihaoyun6** [comment]
首先需要将你的移动设备连接到麦克。在录制电脑屏幕的过程中，点击录制控制器(在菜单栏上)钟的摄像头按钮，并在弹出的设备列表中选择你的iPhone或iPad，此时会弹出一个预览窗口里面显示的就是移动设备的画面。你可以随意放大缩小或者移动这个窗口，以配合你的录制布局

**Comment by cevin** [comment]
可以提前设置好布局然后才开始录制吗？就是在正式录制之前先摆好摄像头、设备窗口等。

**Comment by lihaoyun6** [comment]
> 可以提前设置好布局然后才开始录制吗？就是在正式录制之前先摆好摄像头、设备窗口等。

你可以用QuickRecorder内置的视频修剪器把摆放录制布局的部分给裁掉.
如果没有启用录制结束自动打开修剪器的话, 也可以直接右键点击录屏视频文件, 选择用QuickRecorder打开就可以进入修剪界面
