### ISSUE TITLE
怎么保存...直接关闭 没找到文件。

### ISSUE THREAD

**Issue by qbmiller** [lihaoyun6/QuickRecorder#72]
在默认保存文件夹 也没有。
<img width="258" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/7335567/ae0306c8-ecbc-43f3-953c-0f23a00c563e">
点 方块，暂停 都不行。

**Comment by lihaoyun6** [comment]
正常情况下默认是保存在桌面上的

**Comment by qbmiller** [comment]
还真是
