### ISSUE TITLE
Feature Request: Options for disable mic by default

### ISSUE THREAD

**Issue by whiskerside** [lihaoyun6/QuickRecorder#73]
Would you like to add a setting option to turn off the microphone by default and achieve mute recording?
Thanks.

**Comment by lihaoyun6** [comment]
The microphone is off by default, unless you used it during the last recording. QuickRecorder will remember your last setting.
So just uncheck "Microphone" and it will be off until you want to use it next time

**Comment by whiskerside** [comment]
![image](https://github.com/lihaoyun6/QuickRecorder/assets/101848978/c878e25a-c3fd-4209-9275-380bbe92728e)

aha, I missed this option, it's here.
