### ISSUE TITLE
Capture HDR Content.

### ISSUE THREAD

**Issue by loststars6517** [lihaoyun6/QuickRecorder#76]
wwdc24更新了screencaptureKit, app未来会支持录制hdr内容吗？

**Comment by lihaoyun6** [comment]
我也看到这项特性更新了, 不过我暂时还没有跟进开发. 这几天可能会试一下
但是请注意: 新特性仅在 macOS 15.0+ 上可用, 即使我更新了QuickRecorder支持了新的HDR录制特性, 在旧版系统上也无法使用这些新功能

**Comment by loststars6517** [comment]
是的，我之前就苦于没有app支持录制hdr游戏，obs就算调了色彩空间出来的效果也是错的。
我在Xcode16跑了[官方的实例](https://developer.apple.com/documentation/screencapturekit/capturing_screen_content_in_macos)。发现[官方视频](https://developer.apple.com/videos/play/wwdc2024/10088/)提到的Local Display HDR确实是把HDR内容色彩映射对了， 但是下面的Add screen recording output没法输出录屏；
<img width="1002" alt="Screenshot 2024-06-14 at 23 25 08" src="https://github.com/lihaoyun6/QuickRecorder/assets/125029360/a2ac56e5-42e5-4445-b6bd-1b4f77a2e0a5">
相反，如果把Local Display HDR改回Default (None)，则可以输出录屏文件，但是高光会过曝（就跟以前一样）。
<img width="1017" alt="Screenshot 2024-06-14 at 23 24 56" src="https://github.com/lihaoyun6/QuickRecorder/assets/125029360/c2390943-a654-4bef-8786-dc54f1e2e23b">

**Comment by lihaoyun6** [comment]
刚刚推送的`v1.3.4`版本并不包含HDR支持, 只是一个针对macOS 15的常规兼容性修复. HDR内容录制特性以及会在`v1.3.5`版本中加入, 尽请期待

**Comment by lihaoyun6** [comment]
[QuickRecorder.zip](https://github.com/user-attachments/files/15846365/QuickRecorder.zip)
你试试这个看看能不能用, 我加入了HDR支持

**Comment by loststars6517** [comment]
可以了！非常感谢！
