### ISSUE TITLE
录制屏幕区域-功能无法使用

### ISSUE THREAD

**Issue by mvpyangxu** [lihaoyun6/QuickRecorder#80]
当选择录制部分区域时，弹出下面这个意外退出提示
<img width="515" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/54459610/7972d135-2ef6-4db4-91e2-ee4cf34dccc2">

配置是 m1芯片   macOS  Sonoma 14.1.2

**Comment by lihaoyun6** [comment]
由于 macOS 15 SDK 中加强了对 SwiftUI View 的相等性验证, 所以我的那堆烂代码不出意外的在使用新 SDK 编译后触发了 `AttributeGraph` 崩溃. 😢 十分不好意思, 不过这个问题已经在 v1.3.7 版本中得到了修复.

**Comment by mvpyangxu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mvpyangxu** [comment]
谢谢如此高效的处理👍🏻，刚重新下载了1.3.7可以正常使用了，另外我发现这个版本修改了菜单栏的小图标吗😄
<img width="55" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/54459610/e1649118-1035-4bff-985e-44de3a449d6f">

**Comment by lihaoyun6** [comment]
是的, 哈哈哈哈修改了小图标, 原来的图标太单调换了个指示性更明显的
