### ISSUE TITLE
homebrew 更新版本不是最新版

### ISSUE THREAD

**Issue by guoyida** [lihaoyun6/QuickRecorder#81]
用brew更新，没有抓到最新版1.3.7，还是更新到1.3.2，就报错了

==> Upgrading 1 outdated package:
lihaoyun6/tap/quickrecorder 1.3.1 -> 1.3.2
==> Upgrading quickrecorder
==> Downloading https://github.com/lihaoyun6/QuickRecorder/releases/download/1.3
curl: (22) The requested URL returned error: 404

==> Purging files for version 1.3.2 of Cask quickrecorder
Error: lihaoyun6/tap/quickrecorder: Download failed on Cask 'quickrecorder' with message: Download failed: https://github.com/lihaoyun6/QuickRecorder/releases/download/1.3.2/QuickRecorder_v1.3.2.dmg

**Comment by lihaoyun6** [comment]
好的, 此问题已经得到修复, 更新tap源后即可正常安装

**Comment by TickDracy** [comment]
@lihaoyun6 do you have any idea why the latest version update I got from homebrew is 1.4.5, but Github has a newer one (1.4.6)?
