### ISSUE TITLE
录制画面时音频失常

### ISSUE THREAD

**Issue by JokerQyou** [lihaoyun6/QuickRecorder#82]
macOS 14.5
QuickRecorder 1.3.7 (137)

在单独“录制系统声音”时，声音是正常的。录制有画面时，不论是“录制全屏画面”、“录制屏幕区域”、“录制应用程序”还是“录制窗口内容”，音频都会失常，具体表现是音频随机加速，并在一段时间后随着一声噪音直接失去声音。

录制设置是：

- 色彩空间 sRGB
- 输出格式 MP4/MOV都测试过
- 编码方式 H.264/H.265都测试过
- 在输出中包含Alpha通道 不勾选
- 音频输出格式：AAC/ALAC/FLAC都测试过，都有问题
- 输出质量：AAC格式下测试过320Kbps/256Kbps都有问题

录制时的选项：
<img width="517" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/1465267/65d5fc0b-9d46-49ac-92de-6f393a7b9d8f">

通过终端启动复现后并没有其他日志，仅有一行：`available content has been updated`。

其他可能有用的信息是：

- 外接屏幕（笔记本合盖使用）
- 外接有线耳机（3.5mm），但应该没有影响。即使在控制中心将声音切换到内置扬声器输出，录制画面时也是有问题。

附：“录制窗口内容”时重现的一个样本。

https://github.com/lihaoyun6/QuickRecorder/assets/1465267/1cb177fc-1a60-4248-a93e-3d735b3608fc

**Comment by lihaoyun6** [comment]
好的, 这个问题将在下个版本中得到修复. 近期涉及到提前适配macOS 15. 更换了新的编译SDK, 可能出现一些小bug, 请见谅

**Comment by lihaoyun6** [comment]
此问题已在v1.3.8版本中被修复

**Comment by JokerQyou** [comment]
~~1.3.9 测试仍然没有声音~~
仅录制部分软件没有声音。后续测试之后我再反馈
