### ISSUE TITLE
录制不到播放器窗口

### ISSUE THREAD

**Issue by oyeaono** [lihaoyun6/QuickRecorder#83]
播放器准备好要录制的视频，然后倒计时3秒开始录制，结束之后全程录了桌面，重启电脑也是这样，录不到播放器内容

**Comment by oyeaono** [comment]
版本1.3.7

**Comment by lihaoyun6** [comment]
您好, 可以说一下用的是什么播放器吗. 我用自带的QuickTime没有复现这个问题

**Comment by lihaoyun6** [comment]
请确定使用的是"录制窗口内容"模式  
如果您使用的是应用或者全屏录制模式的话, 请确保没有把您使用的播放器添加到"App黑名单"中, 这也会导致录不上

**Comment by oyeaono** [comment]
> 请确定使用的是"录制窗口内容"模式 如果您使用的是应用或者全屏录制模式的话, 请确保没有把您使用的播放器添加到"App黑名单"中, 这也会导致录不上

我用的可选区域模式，ev2播放器，没更新版本之前还能用，今天更新之后就不好使了

**Comment by oyeaono** [comment]
> > 请确定使用的是"录制窗口内容"模式 如果您使用的是应用或者全屏录制模式的话, 请确保没有把您使用的播放器添加到"App黑名单"中, 这也会导致录不上
> 
> 我用的可选区域模式，ev2播放器，没更新版本之前还能用，今天更新之后就不好使了

还有app黑名单呢，在哪看

**Comment by lihaoyun6** [comment]
您好, 这个不是QuickRecorder的问题, 我下载了最新版的EVPlayer2, 并且用多个旧版QuickRecorder进行测试, 结果都是无法录制到画面的. 是EVPlayer2本身具有防录屏机制
