### ISSUE TITLE
无法打开“QuickRecorder.app”，因为Apple无法检查其是否包含恶意软件。

### ISSUE THREAD

**Issue by drag0n-app** [lihaoyun6/QuickRecorder#86]
下载最新的QuickRecorder_v1.3.9.dmg，提示“无法打开“QuickRecorder.app”，因为Apple无法检查其是否包含恶意软件。”无法打开。
<img width="260" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/7357641/6211078c-9f7d-445e-aa00-4cf96f0a70af">

**Comment by lihaoyun6** [comment]
在访达中右键点击QuickRecorder的图标并选择"打开", 就可以看到允许运行的按钮了
