### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by leavenotrace** [lihaoyun6/QuickRecorder#88]
<img width="666" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/15070465/84ae43b9-5165-495c-8087-b8401b575c74">

**Comment by leavenotrace** [comment]
func record(audioOnly: Bool, filter: SCContentFilter, fastStart: Bool = true) async {
        SCContext.timeOffset = CMTimeMake(value: 0, timescale: 0)
        SCContext.isPaused = false
        SCContext.isResume = false
        
        let recordHDR = ud.bool(forKey: "recordHDR")
        let encoderIsH265 = (ud.string(forKey: "encoder") == Encoder.h265.rawValue) || recordHDR
        
        let conf: SCStreamConfiguration
        if recordHDR {
            if #available(macOS 15, *) {
                conf = SCStreamConfiguration(preset: .captureHDRStreamLocalDisplay)
            } else { conf = SCStreamConfiguration() }
        } else { conf = SCStreamConfiguration() }
        conf.width = 2
        conf.height = 2

**Comment by leavenotrace** [comment]
<img width="1154" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/15070465/513ecd13-51c9-4194-98a5-80cbbe79881e">

**Comment by leavenotrace** [comment]
<img width="1154" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/15070465/91688fc0-9a02-4802-8791-8d1f42b19376">

**Comment by lihaoyun6** [comment]
目前的版本需要用xcode16 beta编译，因为引入了一些只有在macOS 15中才支持的特性以及为了兼容macOS 15的变化。
如果想用xcode15编译的话，请寻找支持hdr录制的前一个版本，那个版本不包含新特性，

**Comment by leavenotrace** [comment]
嗯，明白，谢谢
