### ISSUE TITLE
真心请教：二维码非常好看，方便告知是什么工具生成的吗？

### ISSUE THREAD

**Issue by leopku** [lihaoyun6/QuickRecorder#89]

**Comment by lihaoyun6** [comment]
你说的是扫码赞助的那个二维码吗？二维码本身是我用“草料二维码”这个在线网页生成的，但颜色尺寸和布局是我用ps重新处理过的，并不是直接生成出来就这样

**Comment by leopku** [comment]
> 你说的是扫码赞助的那个二维码吗？二维码本身是我用“草料二维码”这个在线网页生成的，但颜色尺寸和布局是我用ps重新处理过的，并不是直接生成出来就这样

非常感谢
