### ISSUE TITLE
mac brew 1.0.7找不到版本

### ISSUE THREAD

**Issue by LRTFK** [lihaoyun6/QuickRecorder#9]
`$ brew install lihaoyun6/tap/quickrecorder
==> Downloading https://github.com/lihaoyun6/QuickRecorder/releases/download/1.0.7/QuickRecorder_v1.0.7.dmg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'quickrecorder' with message: Download failed: https://github.com/lihaoyun6/QuickRecorder/releases/download/1.0.7/QuickRecorder_v1.0.7.dmg`

**Comment by lihaoyun6** [comment]
刚刚推送的release打包文件名错误, 现在已经重新命名, 更新tap数据后就可以正常安装了

**Comment by solaris256** [comment]
好像还是有点问题，现在的错误是  Error: SHA256 mismatch
Expected: ad551fb1969d98211f5dd1126222e960c8320715a116a8d5b2c4f3ad7fadff98
  Actual: fd47d108b71b6d9e1384c00d8ad6aa2fdb72eec030fbff18af882cd1d88af1aa

**Comment by lihaoyun6** [comment]
> 好像还是有点问题，现在的错误是 Error: SHA256 mismatch Expected: ad551fb1969d98211f5dd1126222e960c8320715a116a8d5b2c4f3ad7fadff98 Actual: fd47d108b71b6d9e1384c00d8ad6aa2fdb72eec030fbff18af882cd1d88af1aa

重新打包的文件sha256变了. 所以我才说的是"更新tap数据后就可以正常安装了"

**Comment by lihaoyun6** [comment]
凡是遇到1.0.7 brew安装失败的, 请先更新我的tap源数据, 然后在安装就可以了
