### ISSUE TITLE
enhancement request: 单纯录制音频时，同时支持录制系统声音与麦克风声音

### ISSUE THREAD

**Issue by CooperZhuang** [lihaoyun6/QuickRecorder#91]
如题，今天与同事语音通话时，想录个音，使用了“录制系统声音”功能，回放时发现仅仅录制了系统声音（也本应如此）。希望增加一个功能，录制音频支持同时双录，一些场景下并不需要录制视频。

**Comment by lihaoyun6** [comment]
因为我没有类似的需求, 所以征求一下意见, 您认为在这种场景下如何处理两条音频流比较合适?
A. 将两条音频流混合之后写入单个音频文件. 这样便于使用, 但是无法后期分离单独的音轨以供编辑  
B. 将两条音频流分别写入两个音频文件. 这样便于后期随时编辑, 但是使用的时候不方便, 需要自行合并
C. 将两条音轨写入一个无画面的视频文件的两条音轨中, 而不是保存音频文件格式

**Comment by CooperZhuang** [comment]
> 因为我没有类似的需求, 所以征求一下意见, 您认为在这种场景下如何处理两条音频流比较合适?
> 
> A. 将两条音频流混合之后写入单个音频文件. 这样便于使用, 但是无法后期分离单独的音轨以供编辑  
> 
> B. 将两条音频流分别写入两个音频文件. 这样便于后期随时编辑, 但是使用的时候不方便, 需要自行合并
> 
> C. 将两条音轨写入一个无画面的视频文件的两条音轨中, 而不是保存音频文件格式  

感谢回复与方案输出的脑力投入，我认为这三种方案都有适合的场景及优缺点，真的很难权衡🥲

理论上 C 方案是一个在使用便捷跟后期空间取得平衡的方案，但缺点可能是文件体积增大、后期分离音轨需要使用视频编辑软件处理增加复杂度。

如果可以我希望都提供，优先 C，有余力再提供 A 跟 B（通过选项控制输出一或两条音轨）。

**Comment by lihaoyun6** [comment]
<img width="359" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/16348097/4cead429-177e-427e-bb4b-57a4eb703995">

我正在进行新功能的测试, 选择了与之前说的完全不同的方案.
目前的方案是QuickRecorder会注册一种新的文件包格式`.qma` (QuickRecorder multi-track audio)
这种文件包格式可以容纳多个音频文件(目前只用到两个), 以及一个属性文件
使用QuickRecorder内置的QMA播放器可以同步播放系统声音和麦克风声音, 并且可以独立调节音量(调节之后, 音量属性会被记录在文件信息里, 下次打开这个文件还是这套音量配置)
如果不需要分享的话, 直接用qma格式保存在硬盘上就行了. 如果需要发给别人, qma播放器自带导出功能, 可以将两个音频文件按照用户设定的音量比例混缩成一个普通的单轨音频文件

**Comment by lihaoyun6** [comment]
此功能已在最新的v1.4.1版本中实装. 请更新到最新版已获取全部新特性

**Comment by CooperZhuang** [comment]
> 此功能已在最新的v1.4.1版本中实装. 请更新到最新版已获取全部新特性

已经用上👍还有个小建议，打开该录音文件之后默认发放音频
