### ISSUE TITLE
一直提示”无法打开 QuickRecorder 因为 Apple 无法监查其是否包含恶意软件“

### ISSUE THREAD

**Issue by pingan8787** [lihaoyun6/QuickRecorder#96]
今天安装 QuickRecorder1.4.0 后，一直无法启动。

<img width="260" alt="image" src="https://github.com/lihaoyun6/QuickRecorder/assets/22870463/d918d62c-dc87-4113-94e6-f42c44011fc0">

QuickRecorder 版本：1.4.0

电脑配置：
MacBook Pro（16 英寸，2019 年）
处理器：2.6 GHz 六核Intel Core i7
系统：MacOS14.5

**Comment by lihaoyun6** [comment]
这是正常现象, 因为我不是苹果的付费开发者. 所以没有取的macOS根安全证书的信任.
只需要在访达中右键点击QuickRecorder的图标, 并选择"打开", 就可以看到强制打开的按钮显示出来了
