### ISSUE TITLE
菜单栏屏幕共享图标

### ISSUE THREAD

**Issue by Dariozuo** [lihaoyun6/QuickRecorder#98]
结束录制后,菜单栏上仍存在提示 quickrecorder正在共享屏幕的一个图标,尽管他没有在共享任何东西.
我也试了一些方法,目前来说,退出应用没有用,重启电脑可以,重新开关共享屏幕权限不可以,重装应用也不可以.
<img width="109" alt="截屏2024-07-07 23 57 12" src="https://github.com/lihaoyun6/QuickRecorder/assets/109204390/541f772d-e828-490b-b895-a9e9834a6379">

**Comment by lihaoyun6** [comment]
使用的是什么录制模式呢? 系统版本和app版本分别是多少?

**Comment by Dariozuo** [comment]
> 使用的是什么录制模式呢? 系统版本和app版本分别是多少?

录制全屏,系统版本 14.5,app 版本是1.4.3,我现在去试试装一下 1.4.4

**Comment by Dariozuo** [comment]
okk,1.4.4 问题解决了,当然也有可能只是我电脑的问题
