### ISSUE TITLE
录制全屏画面菜单中“录制鼠标光标”选项抖动

### ISSUE THREAD

**Issue by monlite** [lihaoyun6/QuickRecorder#99]
设备型号：Macbook Pro 14" M1 Pro
系统版本：Ventura 13.6.7 
显示器：DELL U2417H（1080P）

如视频所示：录制全屏画面菜单选项中的“录制鼠标光标”选项有抖动，其他录制方式中的菜单没有问题。并且在内置显示器和4K显示器没有这个问题，使用1080P显示器就会出现这个问题。

PS：以前没有这个问题，在更新了1.4.2版本后添加了麦克风选择功能后，出现该问题。

https://github.com/lihaoyun6/QuickRecorder/assets/20237633/8c65d582-0ac2-40de-bf65-4d6cef0dc418

**Comment by lihaoyun6** [comment]
此问题已在v1.4.3版本中得到修复, 请检查更新以获取
